version: "3.8"
services:
  elastic:
    container_name: elastic-korpus
    image: elasticsearch:8.6.0
    restart: always
    volumes: 
      - elastic:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
    networks:
      korpus:
  mysql:
    container_name: korpus-mysql
    image: mariadb:10.10
    restart: always
    volumes: 
      - data:/var/lib/mysql
      - init:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=korpus
      - MARIADB_USER=korpus
      - MARIADB_PASSWORD=korpus
      - MARIADB_DATABASE=korpus
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      korpus:
  korpus:
    container_name: korpus
    image: rsj/korpus
    restart: always
    depends_on:
      - elastic
      - mysql
    volumes:
      - private:/private
      - log:/app/log
      - media:/app/media
      - export:/app/export
      - ./gsheets-token.json:/app/gsheets-token.json
      - ./gsheets-credentials.json:/app/gsheets-credentials.json
    labels:
      - "traefik.http.routers.korpus.rule=Host(`korpus.rsj.rs`)"
      - traefik.http.routers.korpus.entrypoints=web
      - traefik.http.routers.korpus.middlewares=redirect-to-https@docker
      - "traefik.http.routers.korpus-secured.rule=Host(`korpus.rsj.rs`)"
      - traefik.http.routers.korpus-secured.entrypoints=websecure
      - traefik.http.routers.korpus-secured.tls.certresolver=letsencrypt
      - traefik.http.routers.korpus-secured.tls=true
    networks:
      korpus:
      recnik:
  qcluster:
    container_name: korpus-qcluster
    image: rsj/korpus
    restart: always
    command: qcluster
    depends_on: 
      - mysql
      - elastic
    volumes:
      - private:/private
      - log:/app/log
      - media:/app/media
      - export:/app/export
      - ./gsheets-token.json:/app/gsheets-token.json
      - ./gsheets-credentials.json:/app/gsheets-credentials.json
    networks:
      korpus:
      recnik:
networks:
  korpus:
    external: true
  recnik:
    external: true
volumes:
  media:
    name: media
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './media'
  data:
    name: data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data'
  init:
    name: init
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './init'
  log:
    name: log
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './log'
  private:
    name: private
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './private'
  elastic:
    name: elastic
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './elastic'
  export:
    name: export
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './export'
