# Generated by Django 3.2.7 on 2021-09-27 10:17

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imenica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomjed', models.CharField(max_length=50, verbose_name='номинатив једнине')),
                ('genjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив једнине')),
                ('datjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив једнине')),
                ('akujed', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив једнине')),
                ('vokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив једнине')),
                ('insjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал једнине')),
                ('lokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив једнине')),
                ('nommno', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив множине')),
                ('genmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив множине')),
                ('datmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив множине')),
                ('akumno', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив множине')),
                ('vokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив множине')),
                ('insmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал множине')),
                ('lokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив множине')),
                ('vrsta', models.IntegerField(choices=[(1, 'апстрактна'), (2, 'заједничка'), (3, 'властита'), (4, 'збирна'), (5, 'градивна'), (6, 'глаголска')], null=True, verbose_name='врста именице')),
                ('recnik_id', models.IntegerField(null=True, verbose_name='ID одреднице у речнику')),
                ('vreme_kreiranja', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време креирања')),
                ('poslednja_izmena', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене')),
            ],
            options={
                'verbose_name': 'именица',
                'verbose_name_plural': 'именице',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OperacijaIzmene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'операција измене',
                'verbose_name_plural': 'операције измена',
            },
        ),
        migrations.CreateModel(
            name='StatusReci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'статус речи',
                'verbose_name_plural': 'статуси речи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VarijantaImenice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('nomjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив једнине')),
                ('genjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив једнине')),
                ('datjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив једнине')),
                ('akujed', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив једнине')),
                ('vokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив једнине')),
                ('insjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал једнине')),
                ('lokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив једнине')),
                ('nommno', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив множине')),
                ('genmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив множине')),
                ('datmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив множине')),
                ('akumno', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив множине')),
                ('vokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив множине')),
                ('insmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал множине')),
                ('lokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив множине')),
            ],
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IzmenaImenice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време')),
                ('imenica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.imenica', verbose_name='именица')),
                ('operacija_izmene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.operacijaizmene', verbose_name='операција измене')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reci.userproxy', verbose_name='корисник')),
            ],
            options={
                'verbose_name': 'измена именице',
                'verbose_name_plural': 'измене именица',
            },
        ),
        migrations.AddField(
            model_name='imenica',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.statusreci', verbose_name='статус речи'),
        ),
        migrations.AddIndex(
            model_name='imenica',
            index=models.Index(fields=['vrsta'], name='reci_imenic_vrsta_db774b_idx'),
        ),
        migrations.AddIndex(
            model_name='imenica',
            index=models.Index(fields=['nomjed'], name='reci_imenic_nomjed_e6a020_idx'),
        ),
    ]
