# Generated by Django 3.2.7 on 2021-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izmenaimenice',
            name='operacija_izmene',
            field=models.PositiveSmallIntegerField(choices=[(1, 'креирана реч'), (2, 'измењена реч')], verbose_name='операција измене'),
        ),
        migrations.DeleteModel(
            name='OperacijaIzmene',
        ),
    ]
