# Generated by Django 3.2.7 on 2021-09-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0002_auto_20210927_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='varijantaimenice',
            name='imenica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reci.imenica', verbose_name='именица'),
            preserve_default=False,
        ),
    ]
