# Generated by Django 3.2.7 on 2021-09-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0003_varijantaimenice_imenica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imenica',
            name='recnik_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID одреднице у речнику'),
        ),
        migrations.AlterField(
            model_name='imenica',
            name='vrsta',
            field=models.IntegerField(blank=True, choices=[(1, 'апстрактна'), (2, 'заједничка'), (3, 'властита'), (4, 'збирна'), (5, 'градивна'), (6, 'глаголска')], null=True, verbose_name='врста именице'),
        ),
    ]
