# Generated by Django 3.2.7 on 2021-10-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0005_auto_20211002_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='glagol',
            name='gpp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='гл.прил. прошли'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='gps',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='гл.прил. садашњи'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='rgp_mj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ргп м.јед.'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='rgp_mm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ргп м.мн.'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='rgp_sj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ргп с.јед.'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='rgp_sm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ргп с.мн.'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='rgp_zj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ргп ж.јед.'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='rgp_zm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ргп ж.мн.'),
        ),
    ]
