# Generated by Django 3.2.7 on 2021-10-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0006_auto_20211002_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oblikglagola',
            name='vreme',
            field=models.IntegerField(choices=[(1, 'презент'), (2, 'футур 1'), (3, 'аорист'), (4, 'имперфекат'), (5, 'императив')], verbose_name='време'),
        ),
    ]
