# Generated by Django 3.2.7 on 2021-10-02 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0007_alter_oblikglagola_vreme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pridev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recnik_id', models.IntegerField(blank=True, null=True, verbose_name='ID одреднице у речнику')),
                ('vreme_kreiranja', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време креирања')),
                ('poslednja_izmena', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.statusreci', verbose_name='статус речи')),
            ],
            options={
                'verbose_name': 'придев',
                'verbose_name_plural': 'придеви',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='oblikglagola',
            options={'ordering': ['vreme'], 'verbose_name': 'глаголски облик', 'verbose_name_plural': 'глаголски облици'},
        ),
        migrations.CreateModel(
            name='VidPrideva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(choices=[(1, 'одређени'), (2, 'неодређени'), (3, 'компаратив'), (4, 'суперлатив')], verbose_name='вид')),
                ('mnomjed', models.TextField(blank=True, null=True, verbose_name='мушки номинатив једнина')),
                ('mgenjed', models.TextField(blank=True, null=True, verbose_name='мушки генитив једнина')),
                ('mdatjed', models.TextField(blank=True, null=True, verbose_name='мушки датив једнина')),
                ('makujed', models.TextField(blank=True, null=True, verbose_name='мушки акузатив једнина')),
                ('mvokjed', models.TextField(blank=True, null=True, verbose_name='мушки вокатив једнина')),
                ('minsjed', models.TextField(blank=True, null=True, verbose_name='мушки инструментал једнина')),
                ('mlokjed', models.TextField(blank=True, null=True, verbose_name='мушки локатив једнина')),
                ('mnommno', models.TextField(blank=True, null=True, verbose_name='мушки номинатив множина')),
                ('mgenmno', models.TextField(blank=True, null=True, verbose_name='мушки генитив множина')),
                ('mdatmno', models.TextField(blank=True, null=True, verbose_name='мушки датив множина')),
                ('makumno', models.TextField(blank=True, null=True, verbose_name='мушки акузатив множина')),
                ('mvokmno', models.TextField(blank=True, null=True, verbose_name='мушки вокатив множина')),
                ('minsmno', models.TextField(blank=True, null=True, verbose_name='мушки инструментал множина')),
                ('mlokmno', models.TextField(blank=True, null=True, verbose_name='мушки локатив множина')),
                ('znomjed', models.TextField(blank=True, null=True, verbose_name='женски номинатив једнина')),
                ('zgenjed', models.TextField(blank=True, null=True, verbose_name='женски генитив једнина')),
                ('zdatjed', models.TextField(blank=True, null=True, verbose_name='женски датив једнина')),
                ('zakujed', models.TextField(blank=True, null=True, verbose_name='женски акузатив једнина')),
                ('zvokjed', models.TextField(blank=True, null=True, verbose_name='женски вокатив једнина')),
                ('zinsjed', models.TextField(blank=True, null=True, verbose_name='женски инструментал једнина')),
                ('zlokjed', models.TextField(blank=True, null=True, verbose_name='женски локатив једнина')),
                ('znommno', models.TextField(blank=True, null=True, verbose_name='женски номинатив множина')),
                ('zgenmno', models.TextField(blank=True, null=True, verbose_name='женски генитив множина')),
                ('zdatmno', models.TextField(blank=True, null=True, verbose_name='женски датив множина')),
                ('zakumno', models.TextField(blank=True, null=True, verbose_name='женски акузатив множина')),
                ('zvokmno', models.TextField(blank=True, null=True, verbose_name='женски вокатив множина')),
                ('zinsmno', models.TextField(blank=True, null=True, verbose_name='женски инструментал множина')),
                ('zlokmno', models.TextField(blank=True, null=True, verbose_name='женски локатив множина')),
                ('snomjed', models.TextField(blank=True, null=True, verbose_name='средњи номинатив једнина')),
                ('sgenjed', models.TextField(blank=True, null=True, verbose_name='средњи генитив једнина')),
                ('sdatjed', models.TextField(blank=True, null=True, verbose_name='средњи датив једнина')),
                ('sakujed', models.TextField(blank=True, null=True, verbose_name='средњи акузатив једнина')),
                ('svokjed', models.TextField(blank=True, null=True, verbose_name='средњи вокатив једнина')),
                ('sinsjed', models.TextField(blank=True, null=True, verbose_name='средњи инструментал једнина')),
                ('slokjed', models.TextField(blank=True, null=True, verbose_name='средњи локатив једнина')),
                ('snommno', models.TextField(blank=True, null=True, verbose_name='средњи номинатив множина')),
                ('sgenmno', models.TextField(blank=True, null=True, verbose_name='средњи генитив множина')),
                ('sdatmno', models.TextField(blank=True, null=True, verbose_name='средњи датив множина')),
                ('sakumno', models.TextField(blank=True, null=True, verbose_name='средњи акузатив множина')),
                ('svokmno', models.TextField(blank=True, null=True, verbose_name='средњи вокатив множина')),
                ('sinsmno', models.TextField(blank=True, null=True, verbose_name='средњи инструментал множина')),
                ('slokmno', models.TextField(blank=True, null=True, verbose_name='средњи локатив множина')),
                ('pridev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.pridev', verbose_name='придев')),
            ],
            options={
                'verbose_name': 'вид придева',
                'verbose_name_plural': 'видови придева',
                'ordering': ['vid'],
            },
        ),
        migrations.CreateModel(
            name='IzmenaPrideva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacija_izmene', models.PositiveSmallIntegerField(choices=[(1, 'креирана реч'), (2, 'измењена реч')], verbose_name='операција измене')),
                ('vreme', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време')),
                ('pridev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.pridev', verbose_name='придев')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reci.userproxy', verbose_name='корисник')),
            ],
            options={
                'verbose_name': 'измена придева',
                'verbose_name_plural': 'измене придева',
            },
        ),
    ]
