# Generated by Django 4.0.3 on 2022-04-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0008_auto_20211002_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varijantaimenice',
            options={'verbose_name': 'варијанта именице', 'verbose_name_plural': 'варијанте именица'},
        ),
        migrations.AddField(
            model_name='glagol',
            name='tgp_mj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='тгп м.јед.'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='tgp_mm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='тгп м.мн.'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='tgp_sj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='тгп с.јед.'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='tgp_sm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='тгп с.мн.'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='tgp_zj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='тгп ж.јед.'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='tgp_zm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='тгп ж.мн.'),
        ),
        migrations.AddIndex(
            model_name='oblikglagola',
            index=models.Index(fields=['glagol', 'vreme'], name='reci_oblikg_glagol__15eb3a_idx'),
        ),
    ]
