# Generated by Django 4.0.3 on 2022-04-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0009_alter_varijantaimenice_options_glagol_tgp_mj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pridev',
            name='lema',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='лема'),
        ),
        migrations.AddIndex(
            model_name='pridev',
            index=models.Index(fields=['lema'], name='reci_pridev_lema_81fd22_idx'),
        ),
    ]
