# Generated by Django 4.0.3 on 2022-04-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0010_pridev_lema_pridev_reci_pridev_lema_81fd22_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridev',
            name='lema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='лема'),
        ),
    ]
