# Generated by Django 4.0.3 on 2022-04-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0010_pridev_lema_pridev_reci_pridev_lema_81fd22_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridev',
            name='lema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='лема'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='makujed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки акузатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='makumno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки акузатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='mdatjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки датив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='mdatmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки датив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='mgenjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки генитив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='mgenmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки генитив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='minsjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки инструментал једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='minsmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки инструментал множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='mlokjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки локатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='mlokmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки локатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='mnomjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки номинатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='mnommno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки номинатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='mvokjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки вокатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='mvokmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='мушки вокатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='sakujed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи акузатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='sakumno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи акузатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='sdatjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи датив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='sdatmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи датив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='sgenjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи генитив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='sgenmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи генитив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='sinsjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи инструментал једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='sinsmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи инструментал множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='slokjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи локатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='slokmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи локатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='snomjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи номинатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='snommno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи номинатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='svokjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи вокатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='svokmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='средњи вокатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zakujed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски акузатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zakumno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски акузатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zdatjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски датив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zdatmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски датив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zgenjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски генитив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zgenmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски генитив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zinsjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски инструментал једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zinsmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски инструментал множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zlokjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски локатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zlokmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски локатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='znomjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски номинатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='znommno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски номинатив множина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zvokjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски вокатив једнина'),
        ),
        migrations.AlterField(
            model_name='vidprideva',
            name='zvokmno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='женски вокатив множина'),
        ),
    ]
