# Generated by Django 4.0.3 on 2022-05-19 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0012_predlog_recca_uzvik_veznik_izmenaveznika_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predlog',
            name='poslednja_izmena',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене'),
        ),
        migrations.AddField(
            model_name='predlog',
            name='vreme_kreiranja',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='време креирања'),
        ),
        migrations.AddField(
            model_name='recca',
            name='poslednja_izmena',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене'),
        ),
        migrations.AddField(
            model_name='recca',
            name='vreme_kreiranja',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='време креирања'),
        ),
        migrations.AddField(
            model_name='uzvik',
            name='poslednja_izmena',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене'),
        ),
        migrations.AddField(
            model_name='uzvik',
            name='vreme_kreiranja',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='време креирања'),
        ),
        migrations.AddField(
            model_name='veznik',
            name='poslednja_izmena',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене'),
        ),
        migrations.AddField(
            model_name='veznik',
            name='vreme_kreiranja',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='време креирања'),
        ),
    ]
