# Generated by Django 4.0.3 on 2022-05-22 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0013_predlog_poslednja_izmena_predlog_vreme_kreiranja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamenica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomjed', models.CharField(max_length=50, verbose_name='номинатив једнине')),
                ('genjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив једнине')),
                ('datjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив једнине')),
                ('akujed', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив једнине')),
                ('vokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив једнине')),
                ('insjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал једнине')),
                ('lokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив једнине')),
                ('nommno', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив множине')),
                ('genmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив множине')),
                ('datmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив множине')),
                ('akumno', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив множине')),
                ('vokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив множине')),
                ('insmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал множине')),
                ('lokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив множине')),
                ('recnik_id', models.IntegerField(blank=True, null=True, verbose_name='ID одреднице у речнику')),
                ('vreme_kreiranja', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време креирања')),
                ('poslednja_izmena', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.statusreci', verbose_name='статус речи')),
            ],
            options={
                'verbose_name': 'заменица',
                'verbose_name_plural': 'заменице',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prilog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komparativ', models.CharField(blank=True, max_length=50, null=True, verbose_name='компаратив')),
                ('superlativ', models.CharField(blank=True, max_length=50, null=True, verbose_name='суперлатив')),
                ('recnik_id', models.IntegerField(blank=True, null=True, verbose_name='ID одреднице у речнику')),
                ('vreme_kreiranja', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време креирања')),
                ('poslednja_izmena', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.statusreci', verbose_name='статус речи')),
            ],
            options={
                'verbose_name': 'прилог',
                'verbose_name_plural': 'прилози',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Broj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив једнине')),
                ('genjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив једнине')),
                ('datjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив једнине')),
                ('akujed', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив једнине')),
                ('vokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив једнине')),
                ('insjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал једнине')),
                ('lokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив једнине')),
                ('nommno', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив множине')),
                ('genmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив множине')),
                ('datmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив множине')),
                ('akumno', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив множине')),
                ('vokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив множине')),
                ('insmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал множине')),
                ('lokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив множине')),
                ('recnik_id', models.IntegerField(blank=True, null=True, verbose_name='ID одреднице у речнику')),
                ('vreme_kreiranja', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време креирања')),
                ('poslednja_izmena', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.statusreci', verbose_name='статус речи')),
            ],
            options={
                'verbose_name': 'број',
                'verbose_name_plural': 'бројеви',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='zamenica',
            index=models.Index(fields=['nomjed'], name='reci_zameni_nomjed_92706f_idx'),
        ),
        migrations.AddIndex(
            model_name='prilog',
            index=models.Index(fields=['komparativ'], name='reci_prilog_kompara_7dd685_idx'),
        ),
        migrations.AddIndex(
            model_name='prilog',
            index=models.Index(fields=['superlativ'], name='reci_prilog_superla_fefc3f_idx'),
        ),
        migrations.AddIndex(
            model_name='broj',
            index=models.Index(fields=['nomjed'], name='reci_broj_nomjed_189718_idx'),
        ),
    ]
