# Generated by Django 4.0.3 on 2022-05-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0014_zamenica_prilog_broj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamenica',
            name='akumno',
        ),
        migrations.RemoveField(
            model_name='zamenica',
            name='datmno',
        ),
        migrations.RemoveField(
            model_name='zamenica',
            name='genmno',
        ),
        migrations.RemoveField(
            model_name='zamenica',
            name='insmno',
        ),
        migrations.RemoveField(
            model_name='zamenica',
            name='lokmno',
        ),
        migrations.RemoveField(
            model_name='zamenica',
            name='nommno',
        ),
        migrations.RemoveField(
            model_name='zamenica',
            name='vokmno',
        ),
        migrations.AlterField(
            model_name='zamenica',
            name='akujed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив'),
        ),
        migrations.AlterField(
            model_name='zamenica',
            name='datjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='датив'),
        ),
        migrations.AlterField(
            model_name='zamenica',
            name='genjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив'),
        ),
        migrations.AlterField(
            model_name='zamenica',
            name='insjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал'),
        ),
        migrations.AlterField(
            model_name='zamenica',
            name='lokjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив'),
        ),
        migrations.AlterField(
            model_name='zamenica',
            name='nomjed',
            field=models.CharField(max_length=50, verbose_name='номинатив'),
        ),
        migrations.AlterField(
            model_name='zamenica',
            name='vokjed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив'),
        ),
        migrations.CreateModel(
            name='VarijantaZamenice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('nomjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив')),
                ('genjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив')),
                ('datjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив')),
                ('akujed', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив')),
                ('vokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив')),
                ('insjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал')),
                ('lokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив')),
                ('zamenica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.zamenica', verbose_name='заменица')),
            ],
            options={
                'verbose_name': 'варијанта заменице',
                'verbose_name_plural': 'варијанте заменица',
            },
        ),
    ]
