# Generated by Django 4.1 on 2022-09-11 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0015_remove_zamenica_akumno_remove_zamenica_datmno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izmenapredloga',
            name='predlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.predlog', verbose_name='предлог'),
        ),
        migrations.AlterField(
            model_name='izmenarecce',
            name='recca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.recca', verbose_name='речца'),
        ),
        migrations.AlterField(
            model_name='izmenauzvika',
            name='uzvik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.uzvik', verbose_name='узвик'),
        ),
        migrations.AlterField(
            model_name='izmenaveznika',
            name='veznik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.veznik', verbose_name='везник'),
        ),
        migrations.CreateModel(
            name='IzmenaZamenice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacija_izmene', models.PositiveSmallIntegerField(choices=[(1, 'креирана реч'), (2, 'измењена реч')], verbose_name='операција измене')),
                ('vreme', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reci.userproxy', verbose_name='корисник')),
                ('zamenica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.zamenica', verbose_name='заменица')),
            ],
            options={
                'verbose_name': 'измена заменице',
                'verbose_name_plural': 'измене заменица',
            },
        ),
        migrations.CreateModel(
            name='IzmenaPriloga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacija_izmene', models.PositiveSmallIntegerField(choices=[(1, 'креирана реч'), (2, 'измењена реч')], verbose_name='операција измене')),
                ('vreme', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време')),
                ('prilog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.prilog', verbose_name='прилог')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reci.userproxy', verbose_name='корисник')),
            ],
            options={
                'verbose_name': 'измена прилога',
                'verbose_name_plural': 'измене прилога',
            },
        ),
        migrations.CreateModel(
            name='IzmenaBroja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacija_izmene', models.PositiveSmallIntegerField(choices=[(1, 'креирана реч'), (2, 'измењена реч')], verbose_name='операција измене')),
                ('vreme', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време')),
                ('broj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.broj', verbose_name='број')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reci.userproxy', verbose_name='корисник')),
            ],
            options={
                'verbose_name': 'измена броја',
                'verbose_name_plural': 'измене бројева',
            },
        ),
    ]
