# Generated by Django 4.1 on 2022-09-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0016_alter_izmenapredloga_predlog_alter_izmenarecce_recca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrojacUnetihReci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_reci', models.IntegerField(default=0, verbose_name='број унетих речи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.userproxy', verbose_name='корисник')),
            ],
            options={
                'verbose_name': 'бројач унетих речи',
                'verbose_name_plural': 'бројачи унетих речи',
            },
        ),
    ]
