# Generated by Django 4.1 on 2022-09-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0017_brojacunetihreci'),
    ]

    operations = [
        migrations.AddField(
            model_name='broj',
            name='vlasnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='креатор'),
        ),
        migrations.AddField(
            model_name='glagol',
            name='vlasnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='креатор'),
        ),
        migrations.AddField(
            model_name='imenica',
            name='vlasnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='креатор'),
        ),
        migrations.AddField(
            model_name='predlog',
            name='vlasnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='креатор'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='vlasnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='креатор'),
        ),
        migrations.AddField(
            model_name='prilog',
            name='vlasnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='креатор'),
        ),
        migrations.AddField(
            model_name='recca',
            name='vlasnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='креатор'),
        ),
        migrations.AddField(
            model_name='uzvik',
            name='vlasnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='креатор'),
        ),
        migrations.AddField(
            model_name='veznik',
            name='vlasnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='креатор'),
        ),
        migrations.AddField(
            model_name='zamenica',
            name='vlasnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='креатор'),
        ),
    ]
