# Generated by Django 4.1 on 2022-09-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0018_broj_vlasnik_glagol_vlasnik_imenica_vlasnik_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrojacUnetihReci',
        ),
    ]
