# Generated by Django 4.1 on 2022-11-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0019_delete_brojacunetihreci'),
    ]

    operations = [
        migrations.AddField(
            model_name='pridev',
            name='dva_vida',
            field=models.BooleanField(default=True, verbose_name='два вида'),
        ),
    ]
