# Generated by Django 4.1 on 2022-11-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0020_pridev_dva_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pridev',
            name='mkakujed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив акузатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mkakumno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив акузатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mkdatjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив датив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mkdatmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив датив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mkgenjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив генитив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mkgenmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив генитив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mkinsjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив инструментал једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mkinsmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив инструментал множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mklokjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив локатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mklokmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив локатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mknomjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив номинатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mknommno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив номинатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mkvokjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив вокатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mkvokmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки компаратив вокатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mnakujed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени акузатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mnakumno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени акузатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mndatjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени датив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mndatmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени датив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mngenjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени генитив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mngenmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени генитив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mninsjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени инструментал једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mninsmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени инструментал множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mnlokjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени локатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mnlokmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени локатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mnnomjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени номинатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mnnommno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени номинатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mnvokjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени вокатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mnvokmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки неодређени вокатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='moakujed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени акузатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='moakumno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени акузатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='modatjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени датив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='modatmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени датив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mogenjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени генитив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mogenmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени генитив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='moinsjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени инструментал једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='moinsmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени инструментал множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='molokjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени локатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='molokmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени локатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='monomjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени номинатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='monommno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени номинатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='movokjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени вокатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='movokmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки одређени вокатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msakujed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив акузатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msakumno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив акузатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msdatjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив датив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msdatmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив датив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msgenjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив генитив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msgenmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив генитив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msinsjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив инструментал једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msinsmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив инструментал множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mslokjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив локатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='mslokmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив локатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msnomjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив номинатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msnommno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив номинатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msvokjed',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив вокатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='msvokmno',
            field=models.TextField(blank=True, null=True, verbose_name='мушки суперлатив вокатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='skakujed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив акузатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='skakumno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив акузатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='skdatjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив датив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='skdatmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив датив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='skgenjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив генитив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='skgenmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив генитив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='skinsjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив инструментал једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='skinsmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив инструментал множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='sklokjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив локатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='sklokmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив локатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='sknomjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив номинатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='sknommno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив номинатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='skvokjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив вокатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='skvokmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи компаратив вокатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spakujed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив акузатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spakumno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив акузатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spdatjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив датив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spdatmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив датив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spgenjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив генитив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spgenmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив генитив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spinsjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив инструментал једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spinsmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив инструментал множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='splokjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив локатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='splokmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив локатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spnomjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив номинатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spnommno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив номинатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spvokjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив вокатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='spvokmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи позитив вокатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssakujed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив акузатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssakumno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив акузатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssdatjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив датив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssdatmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив датив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssgenjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив генитив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssgenmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив генитив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssinsjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив инструментал једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssinsmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив инструментал множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='sslokjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив локатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='sslokmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив локатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssnomjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив номинатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssnommno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив номинатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssvokjed',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив вокатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='ssvokmno',
            field=models.TextField(blank=True, null=True, verbose_name='средњи суперлатив вокатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zkakujed',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив акузатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zkakumno',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив акузатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zkdatjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив датив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zkdatmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив датив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zkgenjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив генитив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zkgenmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив генитив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zkinsjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив инструментал једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zkinsmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив инструментал множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zklokjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив локатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zklokmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив локатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zknomjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив номинатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zknommno',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив номинатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zkvokjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив вокатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zkvokmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски компаратив вокатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpakujed',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив акузатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpakumno',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив акузатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpdatjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив датив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpdatmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив датив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpgenjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив генитив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpgenmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив генитив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpinsjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив инструментал једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpinsmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив инструментал множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zplokjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив локатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zplokmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив локатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpnomjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив номинатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpnommno',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив номинатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpvokjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив вокатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zpvokmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски позитив вокатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsakujed',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив акузатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsakumno',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив акузатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsdatjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив датив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsdatmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив датив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsgenjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив генитив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsgenmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив генитив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsinsjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив инструментал једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsinsmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив инструментал множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zslokjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив локатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zslokmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив локатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsnomjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив номинатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsnommno',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив номинатив множина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsvokjed',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив вокатив једнина'),
        ),
        migrations.AddField(
            model_name='pridev',
            name='zsvokmno',
            field=models.TextField(blank=True, null=True, verbose_name='женски суперлатив вокатив множина'),
        ),
        migrations.DeleteModel(
            name='VidPrideva',
        ),
    ]
