# Generated by Django 4.1 on 2022-11-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0021_pridev_mkakujed_pridev_mkakumno_pridev_mkdatjed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarijantaPrideva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rod', models.IntegerField(choices=[(1, 'мушки'), (2, 'женски'), (3, 'средњи')], verbose_name='род')),
                ('redni_broj', models.IntegerField(verbose_name='редни број')),
                ('onomjed', models.TextField(blank=True, null=True, verbose_name='одређени номинатив једнина')),
                ('ogenjed', models.TextField(blank=True, null=True, verbose_name='одређени генитив једнина')),
                ('odatjed', models.TextField(blank=True, null=True, verbose_name='одређени датив једнина')),
                ('oakujed', models.TextField(blank=True, null=True, verbose_name='одређени акузатив једнина')),
                ('ovokjed', models.TextField(blank=True, null=True, verbose_name='одређени вокатив једнина')),
                ('oinsjed', models.TextField(blank=True, null=True, verbose_name='одређени инструментал једнина')),
                ('olokjed', models.TextField(blank=True, null=True, verbose_name='одређени локатив једнина')),
                ('nnomjed', models.TextField(blank=True, null=True, verbose_name='неодређени номинатив једнина')),
                ('ngenjed', models.TextField(blank=True, null=True, verbose_name='неодређени генитив једнина')),
                ('ndatjed', models.TextField(blank=True, null=True, verbose_name='неодређени датив једнина')),
                ('nakujed', models.TextField(blank=True, null=True, verbose_name='неодређени акузатив једнина')),
                ('nvokjed', models.TextField(blank=True, null=True, verbose_name='неодређени вокатив једнина')),
                ('ninsjed', models.TextField(blank=True, null=True, verbose_name='неодређени инструментал једнина')),
                ('nlokjed', models.TextField(blank=True, null=True, verbose_name='неодређени локатив једнина')),
                ('pnomjed', models.TextField(blank=True, null=True, verbose_name='позитив номинатив једнина')),
                ('pgenjed', models.TextField(blank=True, null=True, verbose_name='позитив генитив једнина')),
                ('pdatjed', models.TextField(blank=True, null=True, verbose_name='позитив датив једнина')),
                ('pakujed', models.TextField(blank=True, null=True, verbose_name='позитив акузатив једнина')),
                ('pvokjed', models.TextField(blank=True, null=True, verbose_name='позитив вокатив једнина')),
                ('pinsjed', models.TextField(blank=True, null=True, verbose_name='позитив инструментал једнина')),
                ('plokjed', models.TextField(blank=True, null=True, verbose_name='позитив локатив једнина')),
                ('knomjed', models.TextField(blank=True, null=True, verbose_name='компаратив номинатив једнина')),
                ('kgenjed', models.TextField(blank=True, null=True, verbose_name='компаратив генитив једнина')),
                ('kdatjed', models.TextField(blank=True, null=True, verbose_name='компаратив датив једнина')),
                ('kakujed', models.TextField(blank=True, null=True, verbose_name='компаратив акузатив једнина')),
                ('kvokjed', models.TextField(blank=True, null=True, verbose_name='компаратив вокатив једнина')),
                ('kinsjed', models.TextField(blank=True, null=True, verbose_name='компаратив инструментал једнина')),
                ('klokjed', models.TextField(blank=True, null=True, verbose_name='компаратив локатив једнина')),
                ('snomjed', models.TextField(blank=True, null=True, verbose_name='суперлатив номинатив једнина')),
                ('sgenjed', models.TextField(blank=True, null=True, verbose_name='суперлатив генитив једнина')),
                ('sdatjed', models.TextField(blank=True, null=True, verbose_name='суперлатив датив једнина')),
                ('sakujed', models.TextField(blank=True, null=True, verbose_name='суперлатив акузатив једнина')),
                ('svokjed', models.TextField(blank=True, null=True, verbose_name='суперлатив вокатив једнина')),
                ('sinsjed', models.TextField(blank=True, null=True, verbose_name='суперлатив инструментал једнина')),
                ('slokjed', models.TextField(blank=True, null=True, verbose_name='суперлатив локатив једнина')),
                ('pridev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.pridev', verbose_name='придев')),
            ],
            options={
                'verbose_name': 'варијанта придева',
                'verbose_name_plural': 'варијанте придева',
                'ordering': ['redni_broj'],
            },
        ),
    ]
