# Generated by Django 4.1 on 2022-11-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0022_varijantaprideva'),
    ]

    operations = [
        migrations.AddField(
            model_name='glagol',
            name='gpp2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='гл.прил. садашњи, варијанта'),
        ),
    ]
