# Generated by Django 4.1 on 2022-12-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0023_glagol_gpp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='prilog',
            name='pozitiv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='позитив'),
        ),
        migrations.AddIndex(
            model_name='prilog',
            index=models.Index(fields=['pozitiv'], name='reci_prilog_pozitiv_0a7479_idx'),
        ),
    ]
