# Generated by Django 3.2.7 on 2021-10-04 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import publikacije.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reci', '0008_auto_20211002_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potkorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=300, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'поткорпус',
                'verbose_name_plural': 'поткорпуси',
            },
        ),
        migrations.CreateModel(
            name='Publikacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=300, verbose_name='наслов')),
                ('naslov_izdanja', models.CharField(blank=True, max_length=300, null=True, verbose_name='наслов издања')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('issn', models.CharField(blank=True, max_length=8, null=True, verbose_name='ISSN')),
                ('izdavac', models.CharField(blank=True, max_length=200, null=True, verbose_name='издавач')),
                ('godina', models.CharField(blank=True, max_length=10, null=True, verbose_name='година')),
                ('volumen', models.CharField(blank=True, max_length=10, null=True, verbose_name='годиште')),
                ('broj', models.CharField(blank=True, max_length=10, null=True, verbose_name='број')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('vreme_unosa', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време уноса')),
                ('skracenica', models.CharField(default='-', max_length=100, verbose_name='скраћеница')),
                ('potkorpus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='publikacije.potkorpus', verbose_name='поткорпус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reci.userproxy', verbose_name='корисник')),
            ],
            options={
                'verbose_name': 'публикација',
                'verbose_name_plural': 'публикације',
            },
        ),
        migrations.CreateModel(
            name='VrstaPublikacije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=300, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'врста публикације',
                'verbose_name_plural': 'врсте публикација',
            },
        ),
        migrations.CreateModel(
            name='TekstPublikacije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('tekst', models.TextField(verbose_name='текст')),
                ('tagovan_tekst', models.TextField(verbose_name='тагован текст')),
                ('publikacija', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publikacije.publikacija', verbose_name='публикација')),
            ],
            options={
                'verbose_name': 'текст публикације',
                'verbose_name_plural': 'текстови публикација',
            },
        ),
        migrations.AddField(
            model_name='publikacija',
            name='vrsta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publikacije.vrstapublikacije', verbose_name='врста'),
        ),
        migrations.CreateModel(
            name='FajlPublikacije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('uploaded_file', models.FileField(upload_to=publikacije.models.get_upload_path, verbose_name='фајл')),
                ('publikacija', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publikacije.publikacija', verbose_name='публикација')),
            ],
            options={
                'verbose_name': 'фајл публикације',
                'verbose_name_plural': 'фајлови публикација',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(blank=True, max_length=50, null=True, verbose_name='име')),
                ('prezime', models.CharField(max_length=50, verbose_name='презиме')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('publikacija', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publikacije.publikacija', verbose_name='публикација')),
            ],
            options={
                'verbose_name': 'аутор',
                'verbose_name_plural': 'аутори',
            },
        ),
    ]
