# Generated by Django 3.2.7 on 2021-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0002_alter_publikacija_vrsta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tekstpublikacije',
            options={'ordering': ['redni_broj'], 'verbose_name': 'текст публикације', 'verbose_name_plural': 'текстови публикација'},
        ),
        migrations.AddIndex(
            model_name='tekstpublikacije',
            index=models.Index(fields=['redni_broj'], name='publikacije_redni_b_d74e38_idx'),
        ),
    ]
