# Generated by Django 3.2.7 on 2021-10-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0003_auto_20211007_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tekstpublikacije',
            name='tagovan_tekst',
            field=models.TextField(blank=True, verbose_name='тагован текст'),
        ),
        migrations.AlterField(
            model_name='tekstpublikacije',
            name='tekst',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
    ]
