# Generated by Django 3.2.7 on 2022-03-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0004_auto_20211011_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPublikacije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('vrsta_filtera', models.IntegerField(choices=[(0, 'Ништа'), (1, 'Уклони фиксан садржај'), (2, 'Уклони хифенацију на крају реда'), (3, 'Уклони број странице на дну'), (4, 'Уклони број странице на врху'), (5, 'Спој линије које се завршавају размаком'), (6, 'Уклони почетне странице')], verbose_name='врста филтера')),
                ('publikacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publikacije.publikacija', verbose_name='публикација')),
            ],
            options={
                'verbose_name': 'филтер публикације',
                'verbose_name_plural': 'филтери публикација',
                'ordering': ['redni_broj'],
            },
        ),
        migrations.AlterModelOptions(
            name='fajlpublikacije',
            options={'ordering': ['redni_broj'], 'verbose_name': 'фајл публикације', 'verbose_name_plural': 'фајлови публикација'},
        ),
        migrations.CreateModel(
            name='ParametarFiltera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('naziv', models.CharField(max_length=30, verbose_name='назив')),
                ('vrednost', models.CharField(blank=True, max_length=1000, null=True, verbose_name='vrednost')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publikacije.filterpublikacije', verbose_name='публикација')),
            ],
            options={
                'verbose_name': 'параметар филтера',
                'verbose_name_plural': 'параметри филтера',
                'ordering': ['redni_broj'],
            },
        ),
    ]
