# Generated by Django 3.2.7 on 2022-03-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0005_auto_20220323_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterpublikacije',
            name='vrsta_filtera',
            field=models.IntegerField(choices=[(0, 'Ништа'), (1, 'Уклони фиксан садржај'), (2, 'Уклони хифенацију'), (3, 'Уклони број странице на дну'), (4, 'Уклони број странице на врху'), (5, 'Спој линије које се завршавају размаком'), (6, 'Уклони почетне странице')], verbose_name='врста филтера'),
        ),
    ]
