# Generated by Django 3.2.7 on 2022-04-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0006_alter_filterpublikacije_vrsta_filtera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='publikacija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publikacije.publikacija', verbose_name='публикација'),
        ),
        migrations.AlterField(
            model_name='fajlpublikacije',
            name='publikacija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publikacije.publikacija', verbose_name='публикација'),
        ),
        migrations.AlterField(
            model_name='filterpublikacije',
            name='vrsta_filtera',
            field=models.IntegerField(choices=[(0, 'Ништа'), (1, 'Уклони фиксан садржај'), (2, 'Уклони хифенацију'), (3, 'Уклони број странице на дну'), (4, 'Уклони број странице на врху'), (5, 'Спој линије које се завршавају размаком'), (6, 'Уклони почетне странице'), (7, 'Латиница у ћирилицу')], verbose_name='врста филтера'),
        ),
        migrations.AlterField(
            model_name='tekstpublikacije',
            name='publikacija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publikacije.publikacija', verbose_name='публикација'),
        ),
    ]
