# Generated by Django 3.2.7 on 2022-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0007_auto_20220419_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='fajlpublikacije',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
    ]
