# Generated by Django 4.0.3 on 2022-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0008_fajlpublikacije_extracted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fajlpublikacije',
            name='extracted',
        ),
        migrations.AddField(
            model_name='fajlpublikacije',
            name='extraction_status',
            field=models.IntegerField(choices=[(0, 'није започета'), (1, 'у току'), (2, 'успешна'), (3, 'неуспешна')], default=0, verbose_name='статус екстракције'),
        ),
    ]
