# Generated by Django 4.1 on 2022-12-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0010_alter_filterpublikacije_vrsta_filtera'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publikacija',
            index=models.Index(fields=['naslov', 'godina'], name='publikacije_naslov_4f247c_idx'),
        ),
    ]
