# Generated by Django 4.1 on 2022-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0011_publikacija_publikacije_naslov_4f247c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='publikacija',
            name='napomena',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='напомена'),
        ),
        migrations.AddField(
            model_name='publikacija',
            name='prevodilac',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='преводилац'),
        ),
        migrations.AddField(
            model_name='publikacija',
            name='prvo_izdanje',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='прво издање'),
        ),
        migrations.AddField(
            model_name='publikacija',
            name='zanr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='жанр'),
        ),
    ]
