# Generated by Django 5.0.3 on 2024-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0012_publikacija_napomena_publikacija_prevodilac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterpublikacije',
            name='vrsta_filtera',
            field=models.IntegerField(choices=[(0, 'Ништа'), (1, 'Уклони фиксан садржај'), (2, 'Уклони хифенацију на крају реда'), (3, 'Уклони број странице на дну'), (4, 'Уклони број странице на врху'), (5, 'Спој линије које се завршавају размаком'), (6, 'Уклони почетне странице'), (7, 'Латиница у ћирилицу'), (8, 'Уклони усамљен број у линији'), (9, 'Уклони празне линије'), (10, 'Уклони хифенацију било где'), (11, 'Спој линије које се не завршавају размаком')], verbose_name='врста филтера'),
        ),
    ]
