# Generated by Django 5.0.3 on 2024-10-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0013_alter_filterpublikacije_vrsta_filtera'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoslednjiRedniBroj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefiks_skracenice', models.CharField(max_length=20, verbose_name='префикс скраћенице')),
                ('redni_broj', models.IntegerField(default=0, verbose_name='редни број')),
            ],
            options={
                'verbose_name': 'последњи редни број скраћенице',
                'verbose_name_plural': 'последњи редни бројеви скраћеница',
                'ordering': ['redni_broj'],
                'indexes': [models.Index(fields=['prefiks_skracenice'], name='publikacije_prefiks_5be3d5_idx')],
            },
        ),
    ]
