# Generated by Django 5.0.3 on 2026-02-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0014_poslednjirednibroj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poslednjirednibroj',
            options={'ordering': ['prefiks_skracenice', 'redni_broj'], 'verbose_name': 'последњи редни број скраћенице', 'verbose_name_plural': 'последњи редни бројеви скраћеница'},
        ),
        migrations.AddField(
            model_name='publikacija',
            name='tom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='том'),
        ),
    ]
