# Generated by Django 3.1.3 on 2021-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='izmenaodrednice',
            old_name='odrednica_id',
            new_name='odrednica',
        ),
        migrations.RenameField(
            model_name='izmenaodrednice',
            old_name='operacija_izmene_id',
            new_name='operacija_izmene',
        ),
        migrations.RenameField(
            model_name='izrazfraza',
            old_name='pripada_odrednici_id',
            new_name='pripada_odrednici',
        ),
        migrations.RenameField(
            model_name='izrazfraza',
            old_name='u_vezi_sa_id',
            new_name='u_vezi_sa',
        ),
        migrations.RenameField(
            model_name='kolokacija',
            old_name='odrednica_id',
            new_name='odrednica',
        ),
        migrations.RenameField(
            model_name='kvalifikatorodrednice',
            old_name='kvalifikator_id',
            new_name='kvalifikator',
        ),
        migrations.RenameField(
            model_name='kvalifikatorodrednice',
            old_name='odrednica_id',
            new_name='odrednica',
        ),
        migrations.RenameField(
            model_name='podznacenje',
            old_name='znacenje_id',
            new_name='znacenje',
        ),
        migrations.RenameField(
            model_name='recukolokaciji',
            old_name='kolokacija_id',
            new_name='kolokacija',
        ),
        migrations.RenameField(
            model_name='recukolokaciji',
            old_name='odrednica_id',
            new_name='odrednica',
        ),
        migrations.RenameField(
            model_name='znacenje',
            old_name='odrednica_id',
            new_name='odrednica',
        ),
        migrations.AddField(
            model_name='podznacenje',
            name='redni_broj',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='редни број'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='znacenje',
            name='redni_broj',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='редни број'),
            preserve_default=False,
        ),
    ]
