# Generated by Django 3.1.3 on 2021-01-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0002_auto_20210108_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odrednica',
            name='glagolski_rod',
            field=models.IntegerField(blank=True, choices=[(0, 'непознат'), (1, 'прелазни'), (2, 'непрелазни'), (3, 'повратни'), (4, 'узајамно повратни')], null=True, verbose_name='глаголски род'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='glagolski_vid',
            field=models.IntegerField(blank=True, choices=[(0, 'непознат'), (1, 'свршени'), (2, 'несвршени'), (3, 'двовидски')], null=True, verbose_name='глаголски вид'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='rod',
            field=models.IntegerField(blank=True, choices=[(1, 'мушки'), (2, 'женски'), (3, 'средњи')], default=0, null=True, verbose_name='род'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='stanje',
            field=models.IntegerField(choices=[(1, 'обрада лексикографа'), (2, 'обрада редактора'), (3, 'обрада уредника'), (4, 'завршена обрада')], default=1, verbose_name='стање'),
        ),
        migrations.CreateModel(
            name='VarijantaOdrednice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('tekst', models.CharField(max_length=50, verbose_name='текст')),
                ('odrednica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odrednice.odrednica', verbose_name='одредница')),
            ],
            options={
                'verbose_name': 'варијанта одреднице',
                'verbose_name_plural': 'варијанте одредница',
            },
        ),
    ]
