# Generated by Django 3.1.3 on 2021-01-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0003_auto_20210110_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='varijantaodrednice',
            name='nastavak',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='наставак'),
        ),
    ]
