# Generated by Django 3.1.3 on 2021-01-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0004_varijantaodrednice_nastavak'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='ijekavski',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ијекавски'),
        ),
        migrations.AddField(
            model_name='varijantaodrednice',
            name='ijekavski',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ијекавски'),
        ),
    ]
