# Generated by Django 3.1.3 on 2021-01-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0005_auto_20210110_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znacenje',
            name='tekst',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='текст'),
        ),
    ]
