# Generated by Django 3.1.3 on 2021-01-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0006_auto_20210110_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvalifikator',
            name='skracenica',
            field=models.CharField(default='-', max_length=15, verbose_name='скраћеница'),
            preserve_default=False,
        ),
    ]
