# Generated by Django 3.1.3 on 2021-01-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0007_kvalifikator_skracenica'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvalifikatorZnacenja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('kvalifikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odrednice.kvalifikator', verbose_name='квалификатор')),
                ('znacenje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odrednice.znacenje', verbose_name='значење')),
            ],
            options={
                'verbose_name': 'квалификатор значења',
                'verbose_name_plural': 'квалификатори значења',
            },
        ),
        migrations.CreateModel(
            name='KvalifikatorPodznacenja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('kvalifikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odrednice.kvalifikator', verbose_name='квалификатор')),
                ('podznacenje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odrednice.podznacenje', verbose_name='подзначење')),
            ],
            options={
                'verbose_name': 'квалификатор подзначења',
                'verbose_name_plural': 'квалификатори подзначења',
            },
        ),
    ]
