# Generated by Django 3.1.3 on 2021-01-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0008_kvalifikatorpodznacenja_kvalifikatorznacenja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izrazfraza',
            name='pripada_odrednici',
        ),
        migrations.RemoveField(
            model_name='izrazfraza',
            name='u_vezi_sa',
        ),
        migrations.AddField(
            model_name='izrazfraza',
            name='odrednica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odrednice.odrednica', verbose_name='одредница'),
        ),
        migrations.AddField(
            model_name='izrazfraza',
            name='podznacenje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odrednice.podznacenje', verbose_name='подзначење'),
        ),
        migrations.AddField(
            model_name='izrazfraza',
            name='redni_broj',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='редни број'),
        ),
        migrations.AddField(
            model_name='izrazfraza',
            name='znacenje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odrednice.znacenje', verbose_name='значење'),
        ),
    ]
