# Generated by Django 3.1.3 on 2021-02-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0004_publikacija_user'),
        ('odrednice', '0009_auto_20210128_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konkordansa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('opis', models.CharField(max_length=2000, verbose_name='опис')),
                ('podznacenje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odrednice.podznacenje', verbose_name='подзначење')),
                ('publikacija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publikacije.publikacija', verbose_name='публикација')),
                ('znacenje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odrednice.znacenje', verbose_name='значење')),
            ],
            options={
                'verbose_name': 'конкорданса',
                'verbose_name_plural': 'конкордансе',
            },
        ),
    ]
