# Generated by Django 3.1.3 on 2021-02-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0010_konkordansa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinonim',
            old_name='ima_sinonim_id',
            new_name='ima_sinonim',
        ),
        migrations.RenameField(
            model_name='sinonim',
            old_name='u_vezi_sa_id',
            new_name='u_vezi_sa',
        ),
    ]
