# Generated by Django 3.1.3 on 2021-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0012_auto_20210205_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odrednica',
            name='glagolski_rod',
            field=models.IntegerField(blank=True, choices=[(1, 'прелазни'), (2, 'непрелазни'), (3, 'повратни'), (4, 'прелазни + повратни'), (5, 'непрелазни + повратни')], null=True, verbose_name='глаголски род'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='glagolski_vid',
            field=models.IntegerField(blank=True, choices=[(1, 'свршени'), (2, 'несвршени'), (3, 'двовидски')], null=True, verbose_name='глаголски вид'),
        ),
    ]
