# Generated by Django 3.1.3 on 2021-02-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0013_auto_20210210_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='opciono_se',
            field=models.NullBooleanField(verbose_name='опционо се'),
        ),
    ]
