# Generated by Django 3.1.3 on 2021-02-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0014_odrednica_opciono_se'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odrednica',
            name='opciono_se',
            field=models.BooleanField(blank=True, null=True, verbose_name='опционо се'),
        ),
    ]
