# Generated by Django 3.1.3 on 2021-02-11 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0015_auto_20210210_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='izrazfraza',
            name='tekst',
            field=models.CharField(default='', max_length=200, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='izrazfraza',
            name='opis',
            field=models.CharField(default='', max_length=2000, verbose_name='опис'),
        ),
        migrations.CreateModel(
            name='KvalifikatorFraze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('izrazfraza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odrednice.izrazfraza', verbose_name='израз фраза')),
                ('kvalifikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odrednice.kvalifikator', verbose_name='квалификатор')),
            ],
        ),
    ]
