# Generated by Django 3.1.3 on 2021-02-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0016_auto_20210211_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izrazfraza',
            name='tekst',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='текст'),
        ),
    ]
