# Generated by Django 3.1.3 on 2021-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0017_auto_20210211_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kvalifikatorfraze',
            options={'verbose_name': 'квалификатор фразе', 'verbose_name_plural': 'квалификатори фраза'},
        ),
        migrations.AddField(
            model_name='znacenje',
            name='znacenje_se',
            field=models.BooleanField(default=False),
        ),
    ]
