# Generated by Django 3.1.3 on 2021-02-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0018_auto_20210213_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antonim',
            options={'ordering': ['redni_broj'], 'verbose_name': 'антоним', 'verbose_name_plural': 'антоними'},
        ),
        migrations.AlterModelOptions(
            name='izrazfraza',
            options={'ordering': ['redni_broj'], 'verbose_name': 'израз фраза', 'verbose_name_plural': 'изрази фразе'},
        ),
        migrations.AlterModelOptions(
            name='konkordansa',
            options={'ordering': ['redni_broj'], 'verbose_name': 'конкорданса', 'verbose_name_plural': 'конкордансе'},
        ),
        migrations.AlterModelOptions(
            name='kvalifikatorfraze',
            options={'ordering': ['redni_broj'], 'verbose_name': 'квалификатор фразе', 'verbose_name_plural': 'квалификатори фраза'},
        ),
        migrations.AlterModelOptions(
            name='kvalifikatorodrednice',
            options={'ordering': ['redni_broj'], 'verbose_name': 'квалификатор одреднице', 'verbose_name_plural': 'квалификатори одредница'},
        ),
        migrations.AlterModelOptions(
            name='kvalifikatorpodznacenja',
            options={'ordering': ['redni_broj'], 'verbose_name': 'квалификатор подзначења', 'verbose_name_plural': 'квалификатори подзначења'},
        ),
        migrations.AlterModelOptions(
            name='kvalifikatorznacenja',
            options={'ordering': ['redni_broj'], 'verbose_name': 'квалификатор значења', 'verbose_name_plural': 'квалификатори значења'},
        ),
        migrations.AlterModelOptions(
            name='podznacenje',
            options={'ordering': ['redni_broj'], 'verbose_name': 'подзначење', 'verbose_name_plural': 'подзначења'},
        ),
        migrations.AlterModelOptions(
            name='recukolokaciji',
            options={'ordering': ['redni_broj'], 'verbose_name': 'реч у колокацији', 'verbose_name_plural': 'речи у колокацији'},
        ),
        migrations.AlterModelOptions(
            name='sinonim',
            options={'ordering': ['redni_broj'], 'verbose_name': 'синоним', 'verbose_name_plural': 'синоними'},
        ),
        migrations.AlterModelOptions(
            name='varijantaodrednice',
            options={'ordering': ['redni_broj'], 'verbose_name': 'варијанта одреднице', 'verbose_name_plural': 'варијанте одредница'},
        ),
        migrations.AlterModelOptions(
            name='znacenje',
            options={'ordering': ['redni_broj', 'znacenje_se'], 'verbose_name': 'значење', 'verbose_name_plural': 'значења'},
        ),
        migrations.AddIndex(
            model_name='antonim',
            index=models.Index(fields=['redni_broj'], name='odrednice_a_redni_b_11f6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='izrazfraza',
            index=models.Index(fields=['redni_broj'], name='odrednice_i_redni_b_e6f091_idx'),
        ),
        migrations.AddIndex(
            model_name='konkordansa',
            index=models.Index(fields=['redni_broj'], name='odrednice_k_redni_b_207116_idx'),
        ),
        migrations.AddIndex(
            model_name='kvalifikatorodrednice',
            index=models.Index(fields=['redni_broj'], name='odrednice_k_redni_b_44576f_idx'),
        ),
        migrations.AddIndex(
            model_name='kvalifikatorpodznacenja',
            index=models.Index(fields=['redni_broj'], name='odrednice_k_redni_b_756e92_idx'),
        ),
        migrations.AddIndex(
            model_name='kvalifikatorznacenja',
            index=models.Index(fields=['redni_broj'], name='odrednice_k_redni_b_aa162f_idx'),
        ),
        migrations.AddIndex(
            model_name='podznacenje',
            index=models.Index(fields=['redni_broj'], name='odrednice_p_redni_b_131c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='recukolokaciji',
            index=models.Index(fields=['redni_broj'], name='odrednice_r_redni_b_8d5166_idx'),
        ),
        migrations.AddIndex(
            model_name='sinonim',
            index=models.Index(fields=['redni_broj'], name='odrednice_s_redni_b_5f4b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='varijantaodrednice',
            index=models.Index(fields=['redni_broj'], name='odrednice_v_redni_b_b46a90_idx'),
        ),
        migrations.AddIndex(
            model_name='znacenje',
            index=models.Index(fields=['redni_broj', 'znacenje_se'], name='odrednice_z_redni_b_03f038_idx'),
        ),
    ]
