# Generated by Django 3.1.3 on 2021-02-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0019_auto_20210213_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='nastavak_ij',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='наставак ијекавски'),
        ),
        migrations.AddField(
            model_name='varijantaodrednice',
            name='nastavak_ij',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='наставак ијекавски'),
        ),
    ]
