# Generated by Django 3.1.3 on 2021-03-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0020_auto_20210226_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='prezent_ij',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='презент'),
        ),
    ]
