# Generated by Django 3.1.3 on 2021-03-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0021_odrednica_prezent_ij'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odrednica',
            name='rod',
            field=models.IntegerField(blank=True, choices=[(1, 'мушки'), (2, 'женски'), (3, 'средњи'), (4, 'мушки и женски')], default=0, null=True, verbose_name='род'),
        ),
    ]
