# Generated by Django 3.1.3 on 2021-03-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0022_auto_20210310_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='rbr_homonima',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='редни број хомонима'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='rod',
            field=models.IntegerField(blank=True, choices=[(1, 'мушки'), (2, 'женски'), (3, 'средњи'), (4, 'мушки и женски'), (5, 'мушки и средњи'), (6, 'женски и средњи')], default=0, null=True, verbose_name='род'),
        ),
    ]
