# Generated by Django 3.1.3 on 2021-03-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0023_auto_20210316_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='izrazfraza',
            name='vezana_odrednica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vezana_odrednica', to='odrednice.odrednica', verbose_name='везана одредница'),
        ),
        migrations.AlterField(
            model_name='izrazfraza',
            name='odrednica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odrednice.odrednica', verbose_name='припада одредници'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='vrsta',
            field=models.IntegerField(choices=[(0, 'именица'), (1, 'глагол'), (2, 'придев'), (3, 'прилог'), (4, 'предлог'), (5, 'заменица'), (6, 'узвик'), (7, 'речца'), (8, 'везник'), (9, 'број'), (10, 'остало')], verbose_name='врста'),
        ),
    ]
