# Generated by Django 3.1.3 on 2021-03-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0024_auto_20210317_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kolokacija',
            options={'ordering': ['redni_broj'], 'verbose_name': 'колокација', 'verbose_name_plural': 'колокације'},
        ),
        migrations.AddField(
            model_name='kolokacija',
            name='redni_broj',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='редни број'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='kolokacija',
            index=models.Index(fields=['redni_broj'], name='odrednice_k_redni_b_476d80_idx'),
        ),
    ]
