# Generated by Django 3.1.3 on 2021-03-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0025_auto_20210322_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kolokacija',
            name='napomena',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='напомена'),
        ),
    ]
