# Generated by Django 3.1.3 on 2021-03-24 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odrednice', '0026_auto_20210322_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='obradjivac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='odrednice_obradjivaca', to=settings.AUTH_USER_MODEL, verbose_name='obradjivac'),
        ),
        migrations.AddField(
            model_name='odrednica',
            name='redaktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odrednice_redaktora', to=settings.AUTH_USER_MODEL, verbose_name='obradjivac'),
        ),
        migrations.AddField(
            model_name='odrednica',
            name='urednik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odrednice_urednika', to=settings.AUTH_USER_MODEL, verbose_name='obradjivac'),
        ),
    ]
