# Generated by Django 3.1.3 on 2021-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0028_auto_20210324_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kvalifikator',
            options={'ordering': ['skracenica'], 'verbose_name': 'квалификатор', 'verbose_name_plural': 'квалификатори'},
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='rbr_homonima',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='редни број хомонима'),
        ),
        migrations.AddIndex(
            model_name='kvalifikator',
            index=models.Index(fields=['skracenica'], name='odrednice_k_skracen_3af7cf_idx'),
        ),
    ]
