# Generated by Django 3.2 on 2021-04-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0030_alter_kvalifikator_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='freetext',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='алтернативни опис'),
        ),
        migrations.AddField(
            model_name='odrednica',
            name='napomene',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='напомене'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='obradjivac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='odrednice_obradjivaca', to='odrednice.userproxy', verbose_name='обрађивач'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='redaktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odrednice_redaktora', to='odrednice.userproxy', verbose_name='редактор'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='urednik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odrednice_urednika', to='odrednice.userproxy', verbose_name='уредник'),
        ),
    ]
