# Generated by Django 3.2 on 2021-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0031_auto_20210427_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odrednica',
            name='rod',
            field=models.IntegerField(blank=True, choices=[(1, 'мушки'), (2, 'женски'), (3, 'средњи'), (4, 'мушки (женски)'), (5, 'женски (мушки)'), (6, 'мушки (средњи)'), (7, 'средњи (мушки)'), (8, 'женски (средњи)'), (9, 'средњи (женски)')], default=0, null=True, verbose_name='род'),
        ),
    ]
