# Generated by Django 3.2 on 2021-04-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0032_alter_odrednica_rod'),
    ]

    operations = [
        migrations.CreateModel(
            name='StastistikaUnosa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme', models.DateTimeField(verbose_name='време генерисања')),
            ],
            options={
                'verbose_name': 'статистика уноса',
                'verbose_name_plural': 'статистике уноса',
                'ordering': ['-vreme'],
            },
        ),
        migrations.CreateModel(
            name='StavkaStatistikeUnosa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_odrednica', models.IntegerField(verbose_name='број одредница')),
                ('broj_znakova', models.IntegerField(verbose_name='број знакова')),
                ('statistika', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odrednice.stastistikaunosa', verbose_name='статистика')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odrednice.userproxy', verbose_name='корисник')),
            ],
            options={
                'verbose_name': 'ставка статистике уноса',
                'verbose_name_plural': 'ставке статистике уноса',
            },
        ),
        migrations.AddIndex(
            model_name='stastistikaunosa',
            index=models.Index(fields=['vreme'], name='odrednice_s_vreme_539420_idx'),
        ),
    ]
