# Generated by Django 3.2 on 2021-04-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0033_auto_20210428_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavkastatistikeunosa',
            name='statistika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odrednice.stastistikaunosa', verbose_name='статистика'),
        ),
    ]
