# Generated by Django 3.2 on 2021-04-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0034_alter_stavkastatistikeunosa_statistika'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StastistikaUnosa',
            new_name='StatistikaUnosa',
        ),
        migrations.RemoveIndex(
            model_name='statistikaunosa',
            name='odrednice_s_vreme_539420_idx',
        ),
        migrations.AddIndex(
            model_name='statistikaunosa',
            index=models.Index(fields=['vreme'], name='odrednice_s_vreme_b813cc_idx'),
        ),
    ]
