# Generated by Django 3.2 on 2021-04-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0035_auto_20210428_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='antonim',
            name='tekst',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='recukolokaciji',
            name='tekst',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='sinonim',
            name='tekst',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='antonim',
            name='u_vezi_sa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antonim_u_vezi_sa', to='odrednice.odrednica', verbose_name='у вези са одредницом'),
        ),
        migrations.AlterField(
            model_name='recukolokaciji',
            name='odrednica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odrednice.odrednica', verbose_name='одредница'),
        ),
        migrations.AlterField(
            model_name='sinonim',
            name='u_vezi_sa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sinonim_u_vezi_sa', to='odrednice.odrednica', verbose_name='у вези са одредницом'),
        ),
    ]
