# Generated by Django 3.2 on 2021-04-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0036_auto_20210428_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='varijantaodrednice',
            name='prezent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='презент'),
        ),
        migrations.AddField(
            model_name='varijantaodrednice',
            name='prezent_ij',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='презент ијекавски'),
        ),
    ]
