# Generated by Django 3.2 on 2021-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0037_auto_20210428_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='varijantaodrednice',
            name='opciono_se',
            field=models.BooleanField(blank=True, null=True, verbose_name='опционо се'),
        ),
    ]
