# Generated by Django 3.2 on 2021-05-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0038_varijantaodrednice_opciono_se'),
    ]

    operations = [
        migrations.CreateModel(
            name='KolokacijaZnacenja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('tekst', models.CharField(blank=True, max_length=2000, null=True, verbose_name='текст')),
                ('znacenje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odrednice.znacenje', verbose_name='значење')),
            ],
            options={
                'verbose_name': 'колокација значења',
                'verbose_name_plural': 'колокације значења',
                'ordering': ['redni_broj'],
            },
        ),
        migrations.CreateModel(
            name='KolokacijaPodznacenja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('tekst', models.CharField(blank=True, max_length=2000, null=True, verbose_name='текст')),
                ('podznacenje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odrednice.podznacenje', verbose_name='значење')),
            ],
            options={
                'verbose_name': 'колокација подзначења',
                'verbose_name_plural': 'колокације подзначења',
                'ordering': ['redni_broj'],
            },
        ),
        migrations.AddIndex(
            model_name='kolokacijaznacenja',
            index=models.Index(fields=['redni_broj'], name='odrednice_k_redni_b_8ecc3c_idx'),
        ),
        migrations.AddIndex(
            model_name='kolokacijapodznacenja',
            index=models.Index(fields=['redni_broj'], name='odrednice_k_redni_b_51c572_idx'),
        ),
    ]
