# Generated by Django 3.2 on 2021-06-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0039_auto_20210530_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOdrednice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'статус одреднице',
                'verbose_name_plural': 'статуси одредница',
            },
        ),
        migrations.AddField(
            model_name='odrednica',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odrednice.statusodrednice', verbose_name='статус одреднице'),
        ),
    ]
