# Generated by Django 3.2 on 2021-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0040_auto_20210616_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusodrednice',
            options={'ordering': ['id'], 'verbose_name': 'статус одреднице', 'verbose_name_plural': 'статуси одредница'},
        ),
        migrations.AddField(
            model_name='stavkastatistikeunosa',
            name='zavrsenih_odrednica',
            field=models.IntegerField(default=0, verbose_name='завршених одредница'),
        ),
        migrations.AddField(
            model_name='stavkastatistikeunosa',
            name='zavrsenih_znakova',
            field=models.IntegerField(default=0, verbose_name='завршених знакова'),
        ),
        migrations.AlterField(
            model_name='stavkastatistikeunosa',
            name='broj_odrednica',
            field=models.IntegerField(verbose_name='сачуваних одредница'),
        ),
        migrations.AlterField(
            model_name='stavkastatistikeunosa',
            name='broj_znakova',
            field=models.IntegerField(verbose_name='сачуваних знакова'),
        ),
    ]
