# Generated by Django 3.2 on 2021-06-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0041_auto_20210623_2035'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='odrednica',
            index=models.Index(fields=['rec'], name='odrednice_o_rec_b34537_idx'),
        ),
    ]
