# Generated by Django 3.2 on 2021-06-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0042_odrednica_odrednice_o_rec_b34537_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='odrednica',
            index=models.Index(fields=['poslednja_izmena'], name='odrednice_o_posledn_085294_idx'),
        ),
    ]
