# Generated by Django 3.2 on 2021-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0043_odrednica_odrednice_o_posledn_085294_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odrednica',
            name='stanje',
            field=models.IntegerField(choices=[(1, 'обрада лексикографа'), (2, 'обрада редактора'), (3, 'обрада уредника'), (4, 'завршена обрада')], default=1, verbose_name='фаза обраде'),
        ),
    ]
