# Generated by Django 3.2 on 2021-07-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0044_alter_odrednica_stanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='konkordansa',
            name='izraz_fraza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odrednice.izrazfraza', verbose_name='фраза'),
        ),
    ]
