# Generated by Django 3.2 on 2021-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0049_odrednica_sortable_rec'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='odrednica',
            index=models.Index(fields=['sortable_rec'], name='odrednice_o_sortabl_8d2b69_idx'),
        ),
    ]
