# Generated by Django 3.2 on 2021-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0050_odrednica_odrednice_o_sortabl_8d2b69_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='odrednica',
            name='odrednice_o_sortabl_8d2b69_idx',
        ),
        migrations.AddIndex(
            model_name='odrednica',
            index=models.Index(fields=['sortable_rec', 'rbr_homonima'], name='odrednice_o_sortabl_d8c16a_idx'),
        ),
    ]
