# Generated by Django 3.2 on 2021-08-12 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0051_auto_20210809_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odrednica',
            name='rod',
            field=models.IntegerField(blank=True, choices=[(1, 'мушки'), (2, 'женски'), (3, 'средњи'), (4, 'мушки (женски)'), (5, 'женски (мушки)'), (6, 'мушки (средњи)'), (7, 'средњи (мушки)'), (8, 'женски (средњи)'), (9, 'средњи (женски)'), (10, 'мушки / женски'), (11, 'мушки / средњи'), (12, 'женски / средњи')], default=0, null=True, verbose_name='род'),
        ),
        migrations.AlterField(
            model_name='varijantaodrednice',
            name='rod',
            field=models.IntegerField(blank=True, choices=[(1, 'мушки'), (2, 'женски'), (3, 'средњи'), (4, 'мушки (женски)'), (5, 'женски (мушки)'), (6, 'мушки (средњи)'), (7, 'средњи (мушки)'), (8, 'женски (средњи)'), (9, 'средњи (женски)'), (10, 'мушки / женски'), (11, 'мушки / средњи'), (12, 'женски / средњи')], default=0, null=True, verbose_name='род'),
        ),
        migrations.CreateModel(
            name='GrupaKvalifikatora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skracenica', models.CharField(max_length=15, verbose_name='скраћеница')),
                ('naziv', models.CharField(max_length=50, verbose_name='назив')),
                ('nadgrupa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odrednice.grupakvalifikatora', verbose_name='надгрупа')),
            ],
            options={
                'verbose_name': 'група квалификатора',
                'verbose_name_plural': 'групе квалификатора',
                'ordering': [django.db.models.functions.comparison.Collate('skracenica', 'utf8mb4_unicode_ci')],
            },
        ),
        migrations.AddField(
            model_name='kvalifikator',
            name='grupa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odrednice.grupakvalifikatora', verbose_name='група'),
        ),
        migrations.AddIndex(
            model_name='grupakvalifikatora',
            index=models.Index(fields=['skracenica'], name='odrednice_g_skracen_0488b0_idx'),
        ),
    ]
