# Generated by Django 3.2 on 2021-08-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0052_auto_20210812_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='prikazi_gl_rod',
            field=models.BooleanField(blank=True, null=True, verbose_name='прикажи глаголски род'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='glagolski_rod',
            field=models.IntegerField(blank=True, choices=[(1, 'прелазни'), (2, 'непрелазни'), (3, 'повратни'), (4, 'прелазни и непрелазни'), (5, 'непрелазни и прелазни'), (6, '(се) облик')], null=True, verbose_name='глаголски род'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='glagolski_vid',
            field=models.IntegerField(blank=True, choices=[(1, 'свршени'), (2, 'несвршени'), (3, 'свршени и несвршени'), (4, 'несвршени и свршени'), (5, 'свршени (несвршени)'), (6, 'несвршени (свршени)')], null=True, verbose_name='глаголски вид'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='rod',
            field=models.IntegerField(blank=True, choices=[(1, 'мушки'), (2, 'женски'), (3, 'средњи'), (4, 'мушки (женски)'), (5, 'женски (мушки)'), (6, 'мушки (средњи)'), (7, 'средњи (мушки)'), (8, 'женски (средњи)'), (9, 'средњи (женски)'), (10, 'мушки / женски'), (11, 'мушки / средњи'), (12, 'женски / средњи'), (13, '---')], default=0, null=True, verbose_name='род'),
        ),
        migrations.AlterField(
            model_name='varijantaodrednice',
            name='rod',
            field=models.IntegerField(blank=True, choices=[(1, 'мушки'), (2, 'женски'), (3, 'средњи'), (4, 'мушки (женски)'), (5, 'женски (мушки)'), (6, 'мушки (средњи)'), (7, 'средњи (мушки)'), (8, 'женски (средњи)'), (9, 'средњи (женски)'), (10, 'мушки / женски'), (11, 'мушки / средњи'), (12, 'женски / средњи'), (13, '---')], default=0, null=True, verbose_name='род'),
        ),
    ]
