# Generated by Django 3.2 on 2021-08-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0054_alter_odrednica_glagolski_rod'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='ima_se_znacenja',
            field=models.BooleanField(blank=True, null=True, verbose_name='има значења за ~ ce'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='glagolski_rod',
            field=models.IntegerField(blank=True, choices=[(1, 'прелазни'), (2, 'непрелазни'), (3, 'повратни'), (4, 'прелазни и непрелазни'), (5, 'непрелазни и прелазни'), (6, 'прелазни (непрелазни)'), (7, 'непрелазни (прелазни)')], null=True, verbose_name='глаголски род'),
        ),
    ]
