# Generated by Django 3.2.7 on 2021-09-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0055_auto_20210816_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='varijantaodrednice',
            name='ravnopravna',
            field=models.BooleanField(default=True, verbose_name='равноправна'),
        ),
    ]
