# Generated by Django 3.2.7 on 2021-09-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0056_varijantaodrednice_ravnopravna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafikonunosa',
            name='tip',
            field=models.IntegerField(choices=[(1, 'недељни принос'), (2, 'месечни принос'), (3, 'годишњи принос'), (4, 'недељни кумулативно'), (5, 'месечни кумулативно'), (6, 'годишњи кумулативно'), (7, 'недељно по словима'), (8, 'месечно по словима'), (9, 'укупно по словима')], verbose_name='тип графикона'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='obradjivac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odrednice_obradjivaca', to='odrednice.userproxy', verbose_name='обрађивач'),
        ),
    ]
