# Generated by Django 3.2.7 on 2021-09-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0057_auto_20210919_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavkastatistikeunosa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odrednice.userproxy', verbose_name='корисник'),
        ),
    ]
