# Generated by Django 3.2.7 on 2021-09-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0058_alter_stavkastatistikeunosa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varijantaodrednice',
            name='ravnopravna',
        ),
    ]
