# Generated by Django 3.2.7 on 2021-09-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0059_remove_varijantaodrednice_ravnopravna'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='ravnopravne_varijante',
            field=models.BooleanField(default=True, verbose_name='равноправне варијанте'),
        ),
    ]
