# Generated by Django 3.2.7 on 2021-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0060_odrednica_ravnopravne_varijante'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodvrstaReci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.IntegerField(choices=[(0, 'именица'), (1, 'глагол'), (2, 'придев'), (3, 'прилог'), (4, 'предлог'), (5, 'заменица'), (6, 'узвик'), (7, 'речца'), (8, 'везник'), (9, 'број'), (10, 'остало')], verbose_name='врста')),
                ('naziv', models.CharField(max_length=80, verbose_name='назив')),
                ('skracenica', models.CharField(max_length=15, verbose_name='скраћеница')),
            ],
            options={
                'verbose_name': 'статус одреднице',
                'verbose_name_plural': 'статуси одредница',
                'ordering': ['vrsta', 'id'],
            },
        ),
    ]
