# Generated by Django 3.2.7 on 2021-09-25 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0061_podvrstareci'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednica',
            name='podvrsta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odrednice.podvrstareci', verbose_name='подврста'),
        ),
    ]
