# Generated by Django 3.2.7 on 2021-09-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0062_odrednica_podvrsta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podvrstareci',
            options={'ordering': ['vrsta', 'id'], 'verbose_name': 'подврста речи', 'verbose_name_plural': 'подврсте речи'},
        ),
    ]
