# Generated by Django 4.1.5 on 2023-02-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0063_alter_podvrstareci_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='konkordansa',
            name='korpus_izvor_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ИД извора у корпусу'),
        ),
    ]
