# Generated by Django 4.1.5 on 2023-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0065_remove_konkordansa_publikacija'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antonim',
            name='ima_antonim',
        ),
        migrations.RemoveField(
            model_name='antonim',
            name='u_vezi_sa',
        ),
        migrations.RemoveField(
            model_name='sinonim',
            name='ima_sinonim',
        ),
        migrations.RemoveField(
            model_name='sinonim',
            name='u_vezi_sa',
        ),
        migrations.AddField(
            model_name='antonim',
            name='ident1',
            field=models.IntegerField(default=1, verbose_name='идентификатор везе 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antonim',
            name='ident2',
            field=models.IntegerField(default=1, verbose_name='идентификатор везе 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antonim',
            name='vrsta1',
            field=models.IntegerField(choices=[(1, 'одредница'), (2, 'значење'), (3, 'подзначење')], default=1, verbose_name='врста везе 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antonim',
            name='vrsta2',
            field=models.IntegerField(choices=[(1, 'одредница'), (2, 'значење'), (3, 'подзначење')], default=1, verbose_name='врста везе 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinonim',
            name='ident1',
            field=models.IntegerField(default=1, verbose_name='идентификатор везе 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinonim',
            name='ident2',
            field=models.IntegerField(default=1, verbose_name='идентификатор везе 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinonim',
            name='vrsta1',
            field=models.IntegerField(choices=[(1, 'одредница'), (2, 'значење'), (3, 'подзначење')], default=1, verbose_name='врста везе 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinonim',
            name='vrsta2',
            field=models.IntegerField(choices=[(1, 'одредница'), (2, 'значење'), (3, 'подзначење')], default=1, verbose_name='врста везе 2'),
            preserve_default=False,
        ),
    ]
