# Generated by Django 4.1.5 on 2023-02-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0066_remove_antonim_ima_antonim_remove_antonim_u_vezi_sa_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='antonim',
            index=models.Index(fields=['vrsta1', 'ident1'], name='odrednice_a_vrsta1_e36851_idx'),
        ),
        migrations.AddIndex(
            model_name='antonim',
            index=models.Index(fields=['vrsta2', 'ident2'], name='odrednice_a_vrsta2_315351_idx'),
        ),
        migrations.AddIndex(
            model_name='sinonim',
            index=models.Index(fields=['vrsta1', 'ident1'], name='odrednice_s_vrsta1_24b708_idx'),
        ),
        migrations.AddIndex(
            model_name='sinonim',
            index=models.Index(fields=['vrsta2', 'ident2'], name='odrednice_s_vrsta2_39ccfb_idx'),
        ),
    ]
