# Generated by Django 4.1.5 on 2023-10-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0067_antonim_odrednice_a_vrsta1_e36851_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='odrednica',
            index=models.Index(fields=['obradjivac'], name='odrednice_o_obradji_543d43_idx'),
        ),
    ]
