# Generated by Django 5.0.3 on 2025-07-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0068_odrednica_odrednice_o_obradji_543d43_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odrednica',
            name='freetext',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='алтернативни опис'),
        ),
        migrations.AlterField(
            model_name='odrednica',
            name='napomene',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='напомене'),
        ),
    ]
