# Generated by Django 3.1.3 on 2020-12-05 15:05

from django.db import migrations, models
import django.db.models.deletion
import publikacije.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(blank=True, max_length=50, null=True, verbose_name='име')),
                ('prezime', models.CharField(max_length=50, verbose_name='презиме')),
            ],
            options={
                'verbose_name': 'аутор',
                'verbose_name_plural': 'аутори',
            },
        ),
        migrations.CreateModel(
            name='Publikacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=300, verbose_name='наслов')),
                ('naslov_izdanja', models.CharField(blank=True, max_length=300, null=True, verbose_name='наслов издања')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('issn', models.CharField(blank=True, max_length=8, null=True, verbose_name='ISSN')),
                ('izdavac', models.CharField(blank=True, max_length=200, null=True, verbose_name='издавач')),
                ('godina', models.CharField(blank=True, max_length=10, null=True, verbose_name='година')),
                ('volumen', models.CharField(blank=True, max_length=10, null=True, verbose_name='годиште')),
                ('broj', models.CharField(blank=True, max_length=10, null=True, verbose_name='број')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('vreme_unosa', models.DateTimeField(verbose_name='време уноса')),
            ],
            options={
                'verbose_name': 'публикација',
                'verbose_name_plural': 'публикације',
            },
        ),
        migrations.CreateModel(
            name='VrstaPublikacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=300, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'врста публикације',
                'verbose_name_plural': 'врсте публикација',
            },
        ),
        migrations.CreateModel(
            name='TekstPublikacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('tekst', models.TextField(verbose_name='текст')),
                ('publikacija', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publikacije.publikacija', verbose_name='публикација')),
            ],
            options={
                'verbose_name': 'текст публикације',
                'verbose_name_plural': 'текстови публикација',
            },
        ),
        migrations.AddField(
            model_name='publikacija',
            name='vrsta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publikacije.vrstapublikacije', verbose_name='врста'),
        ),
        migrations.CreateModel(
            name='FajlPublikacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('uploaded_file', models.FileField(upload_to=publikacije.models.get_upload_path, verbose_name='фајл')),
                ('publikacija', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publikacije.publikacija', verbose_name='публикација')),
            ],
            options={
                'verbose_name': 'фајл публикације',
                'verbose_name_plural': 'фајлови публикација',
            },
        ),
        migrations.CreateModel(
            name='AutorPublikacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publikacije.autor', verbose_name='аутор')),
                ('publikacija', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publikacije.publikacija', verbose_name='публикација')),
            ],
            options={
                'verbose_name': 'аутор публикације',
                'verbose_name_plural': 'аутори публикација',
            },
        ),
    ]
