# Generated by Django 3.1.3 on 2020-12-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='publikacija',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='publikacije.publikacija', verbose_name='публикација'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='redni_broj',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='редни број'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AutorPublikacije',
        ),
    ]
