# Generated by Django 3.1.3 on 2020-12-07 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publikacije', '0003_publikacija_potkorpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='publikacija',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='корисник'),
            preserve_default=False,
        ),
    ]
