# Generated by Django 4.1.5 on 2023-05-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publikacije', '0006_auto_20210313_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fajlpublikacije',
            name='publikacija',
        ),
        migrations.RemoveField(
            model_name='publikacija',
            name='user',
        ),
        migrations.RemoveField(
            model_name='publikacija',
            name='vrsta',
        ),
        migrations.RemoveField(
            model_name='tekstpublikacije',
            name='publikacija',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='FajlPublikacije',
        ),
        migrations.DeleteModel(
            name='Publikacija',
        ),
        migrations.DeleteModel(
            name='TekstPublikacije',
        ),
        migrations.DeleteModel(
            name='VrstaPublikacije',
        ),
    ]
