from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Imenica)
admin.site.register(VarijantaImenice)
admin.site.register(IzmenaImenice)
admin.site.register(Glagol)
admin.site.register(OblikGlagola)
admin.site.register(VarijanteGlagola)
admin.site.register(IzmenaGlagola)
admin.site.register(Pridev)
# admin.site.register(VidPrideva)
admin.site.register(IzmenaPrideva)
admin.site.register(Predlog)
admin.site.register(IzmenaPredloga)
admin.site.register(Uzvik)
admin.site.register(IzmenaUzvika)
admin.site.register(Recca)
admin.site.register(IzmenaRecce)
admin.site.register(Veznik)
admin.site.register(IzmenaVeznika)
admin.site.register(Zamenica)
admin.site.register(VarijantaZamenice)
admin.site.register(IzmenaZamenice)
admin.site.register(Broj)
admin.site.register(IzmenaBroja)
admin.site.register(Prilog)
admin.site.register(IzmenaPriloga)
