version: "3.9"
services:
  web:
    build: .
    container_name: extractor
    ports:
      - "8090:8090"
    depends_on:
      - gotenberg
  gotenberg:
    image: gotenberg/gotenberg:7
    expose:
      - "3000"
    ports:
      - "3000:3000"