from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .rest import (AntonimList, AntonimDetail, SinonimList, SinonimDetail,
                   KolokacijaList, KolokacijaDetail, RecUKolokacijiList,
                   RecUKolokacijiDetail, ZnacenjeDetail, ZnacenjeList,
                   PodznacenjeList, PodznacenjeDetail, IzrazFrazaList,
                   IzrazFrazaDetail, KvalifikatorOdredniceList,
                   KvalifikatorOdredniceDetail, KvalifikatorList,
                   KvalifikatorDetail, IzmenaOdredniceList,
                   IzmenaOdredniceDetail, OperacijaIzmeneOdredniceList,
                   OperacijaIzmeneOdredniceDetail, OdrednicaList,
                   OdrednicaPopularList, OdrednicaLatestList, OdrednicaDetail,
                   api_save_odrednica)

app_name = 'одреднице'

urlpatterns = [
    path('antonim/', AntonimList.as_view(),
         name='antonim-list'),
    path('antonim/<int:pk>/', AntonimDetail.as_view(),
         name='antonim-detail'),
    path('sinonim/', SinonimList.as_view(),
         name='sinonim-list'),
    path('sinonim/<int:pk>/', SinonimDetail.as_view(),
         name='sinonim-detail'),
    path('kolokacija/', KolokacijaList.as_view(),
         name='kolokacija-list'),
    path('kolokacija/<int:pk>/', KolokacijaDetail.as_view(),
         name='kolokacija-detail'),
    path('rec-u-kolokaciji/', RecUKolokacijiList.as_view(),
         name='rec-u-kolokaciji-list'),
    path('rec-u-kolokaciji/<int:pk>/', RecUKolokacijiDetail.as_view(),
         name='rec-u-kolokaciji-detail'),
    path('znacenje/', ZnacenjeList.as_view(),
         name='znacenje-list'),
    path('znacenje/<int:pk>/', ZnacenjeDetail.as_view(),
         name='znacenje-detail'),
    path('podznacenje/', PodznacenjeList.as_view(), name='podznacenje-list'),
    path('podznacenje/<int:pk>/', PodznacenjeDetail.as_view(),
         name='podznacenje-detail'),
    path('izraz-fraza/', IzrazFrazaList.as_view(),
         name='izrazfraza-list'),
    path('izraz-fraza/<int:pk>/', IzrazFrazaDetail.as_view(),
         name='izrazfraza-detail'),
    path('kvalifikator-odrednice/', KvalifikatorOdredniceList.as_view(),
         name='kvalifikator-odrednice-list'),
    path('kvalifikator-odrednice/<int:pk>/',
         KvalifikatorOdredniceDetail.as_view(),
         name='kvalifikator-odrednice-detail'),
    path('kvalifikator/', KvalifikatorList.as_view(),
         name='kvalifikator-list'),
    path('kvalifikator/<int:pk>/', KvalifikatorDetail.as_view(),
         name='kvalifikator-detail'),
    path('izmena-odrednice/', IzmenaOdredniceList.as_view(),
         name='izmena-odrednice-list'),
    path('izmena-odrednice/<int:pk>/', IzmenaOdredniceDetail.as_view(),
         name='izmena-odrednice-detail'),
    path('operacija-izmene-odrednice/',
         OperacijaIzmeneOdredniceList.as_view(),
         name='operacija-izmene-list'),
    path('operacija-izmene-odrednice/<int:pk>/',
         OperacijaIzmeneOdredniceDetail.as_view(),
         name='operacija-izmene-detail'),
    path('odrednica/',
         OdrednicaList.as_view(),
         name='odrednica-list'),
    path('odrednica-latest/',
         OdrednicaLatestList.as_view(),
         name='odrednica-latest-list'),
    path('odrednica-changed/',
         OdrednicaLatestList.as_view(),
         name='odrednica-changed-list'),
    path('odrednica-popular/',
         OdrednicaPopularList.as_view(),
         name='odrednica-popular-list'),
    path('odrednica/<int:pk>/',
         OdrednicaDetail.as_view(),
         name='odrednica-detail'),
    path('save-odrednica/', api_save_odrednica),
]

urlpatterns = format_suffix_patterns(urlpatterns)
