# Generated by Django 3.1.3 on 2020-12-15 21:00

from django.db import migrations, models
import django.db.models.deletion
import render.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipRenderovanogDokumenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'тип рендерованог документа',
                'verbose_name_plural': 'типови рендерованог документа',
            },
        ),
        migrations.CreateModel(
            name='RenderovaniDokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme_rendera', models.DateTimeField()),
                ('opis', models.CharField(max_length=100, verbose_name='опис')),
                ('rendered_file', models.FileField(upload_to=render.models.get_rendered_file_path, verbose_name='фајл')),
                ('napomena', models.TextField()),
                ('tip_dokumenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='render.tiprenderovanogdokumenta', verbose_name='тип документа')),
            ],
            options={
                'verbose_name': 'рендеровани документ',
                'verbose_name_plural': 'рендеровани документи',
            },
        ),
    ]
