# Generated by Django 3.1.3 on 2021-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='renderovanidokument',
            index=models.Index(fields=['vreme_rendera'], name='render_rend_vreme_r_6a6800_idx'),
        ),
    ]
