# Generated by Django 3.1.3 on 2021-03-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_auto_20210304_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderovanidokument',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pdf'), (2, 'docx')], default=1, verbose_name='тип фајла'),
        ),
    ]
