# Generated by Django 3.2 on 2021-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odrednice', '0044_alter_odrednica_stanje'),
        ('render', '0003_renderovanidokument_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiprenderovanogdokumenta',
            name='statusi',
            field=models.ManyToManyField(to='odrednice.StatusOdrednice'),
        ),
    ]
