# Generated by Django 5.0.3 on 2026-02-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0004_tiprenderovanogdokumenta_statusi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiprenderovanogdokumenta',
            name='file_prefix',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='префикс фајла'),
        ),
    ]
