[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[log]
  # Default: "ERROR"
  level = "DEBUG"

  # Default: os.Stdout
  filePath = "/log/traefik.log"

  # Format is either "json" or "common". Default: "common"
  # format = "json"

[accessLog]
  # Default: os.Stdout
  filePath = "/log/access.log"

  # Format is either "json" or "common". Default: "common"
  # format = "json"

[api]
  # Enable the API in insecure mode. Default: false
  insecure = true

  # Enabled Dashboard. Default: true
  # dashboard = false

[ping]
  # Name of the related entry point. Default: "traefik"
  # entryPoint = "traefik"

[providers.docker]
  # Docker server endpoint. Can be a tcp or a unix socket endpoint. Default: "unix:///var/run/docker.sock"
  # endpoint = "tcp://10.10.10.10:2375"

  # Default host rule. Default: "Host(`{{ normalize .Name }}`)"
  # defaultRule = "Host(`{{ normalize .Name }}.docker.localhost`)"

  # Expose containers by default in traefik. Default: true
  # exposedByDefault = false

[certificatesresolvers]
  [certificatesresolvers.letsencrypt]
    [certificatesresolvers.letsencrypt.acme]
      email = "office@ftninformatika.com"
      storage = "/letsencrypt/acme.json"
      [certificatesresolvers.letsencrypt.acme.httpchallenge]
        entrypoint = "web"

