version: "3.8"
services:
  elastic:
    container_name: elastic-recnik
    image: elasticsearch:8.6.0
    restart: always
    volumes: 
      - elastic:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
    networks:
      recnik:
  mysql:
    container_name: recnik-mysql
    image: mariadb:10.10
    restart: always
    volumes: 
      - data:/var/lib/mysql
      - init:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=recnik
      - MARIADB_USER=recnik
      - MARIADB_PASSWORD=recnik
      - MARIADB_DATABASE=recnik
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      recnik:
  korpus:
    container_name: recnik
    image: rsj/recnik
    restart: always
    depends_on:
      - elastic
      - mysql
    volumes:
      - private:/private
      - log:/app/log
      - media:/app/media
    labels:
      - "traefik.http.routers.recnik.rule=Host(`recnik.rsj.rs`)"
      - traefik.http.routers.recnik.entrypoints=web
      - traefik.http.routers.recnik.middlewares=redirect-to-https@docker
      - "traefik.http.routers.recnik-secured.rule=Host(`recnik.rsj.rs`)"
      - traefik.http.routers.recnik-secured.entrypoints=websecure
      - traefik.http.routers.recnik-secured.tls.certresolver=letsencrypt
      - traefik.http.routers.recnik-secured.tls=true
    networks:
      recnik:
networks:
  recnik:
    external: true
volumes:
  media:
    name: media
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './media'
  data:
    name: data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data'
  init:
    name: init
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './init'
  log:
    name: log
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './log'
  private:
    name: private
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './private'
  elastic:
    name: elastic
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './elastic'
