version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_DATABASE=recnik # name you want for the database
      - MYSQL_USER=recnik # change to whatever username you want
      - MYSQL_PASSWORD=recnik #change to the password you want for user
      - MYSQL_ROOT_PASSWORD=root #change to good root password
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
    
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db