version: "3.8"
services:
  elastic:
    container_name: elastic-recnik
    image: elasticsearch:8.12.2
    restart: always
    volumes: 
      - recnik-elastic:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
    networks:
      recnik:
    healthcheck:
      test: curl -s http://elastic-recnik:9200 >/dev/null || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
  mysql:
    container_name: recnik-mysql
    image: mariadb:10.10
    restart: always
    volumes: 
      - recnik-data:/var/lib/mysql
      - recnik-init:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=recnik
      - MARIADB_USER=recnik
      - MARIADB_PASSWORD=recnik
      - MARIADB_DATABASE=recnik
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      recnik:
    healthcheck:
      test: mysqladmin ping -h localhost -u root -precnik
      timeout: 5s
      retries: 10
  recnik:
    container_name: recnik
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      elastic:
        condition: service_healthy
    volumes:
      - recnik-private:/private
      - recnik-log:/app/log
      - recnik-media:/app/media
    networks:
      recnik:
  nginx:
    container_name: recnik-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    depends_on: 
      - recnik
    volumes:
      - recnik-log:/var/log/nginx
      - recnik-media:/media
    labels:
      - "traefik.http.routers.recnik.rule=Host(`recnik.rsj.rs`)"
      - traefik.http.routers.recnik.entrypoints=web
      - traefik.http.routers.recnik.middlewares=redirect-to-https@docker
      - "traefik.http.routers.recnik-secured.rule=Host(`recnik.rsj.rs`)"
      - traefik.http.routers.recnik-secured.entrypoints=websecure
      - traefik.http.routers.recnik-secured.tls.certresolver=letsencrypt
      - traefik.http.routers.recnik-secured.tls=true
    networks:
      recnik:
networks:
  recnik:
    external: true
volumes:
  recnik-media:
    name: recnik-media
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './media'
  recnik-data:
    name: recnik-data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data'
  recnik-init:
    name: recnik-init
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './init'
  recnik-log:
    name: recnik-log
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './log'
  recnik-private:
    name: recnik-private
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './private'
  recnik-elastic:
    name: recnik-elastic
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './elastic'
