FROM node:20-alpine AS angular
RUN npm update -g
RUN mkdir /app
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json /app/
RUN npm ci
COPY frontend /app
RUN npm run build -- --output-path=/app/frontend/dist/

FROM python:3.11-slim-bookworm AS django
RUN apt-get -y update
RUN apt-get -y install pkg-config gcc default-libmysqlclient-dev graphviz-dev libffi-dev libmagic1 libtiff-dev libopenjp2-7-dev liblcms-dev zlib1g-dev libjpeg-dev musl-dev
RUN /usr/local/bin/python3 -m pip install --upgrade pip
RUN pip3 install -U setuptools
COPY backend/requirements.txt /app/requirements.txt
RUN pip3 install -r /app/requirements.txt
COPY backend /app
RUN mkdir -p /app/staticfiles
WORKDIR /app
RUN mkdir /private
RUN touch /private/secrets
RUN rm -rf /app/log
RUN mkdir /app/log
ARG django_settings=prod
ENV DJANGO_SETTINGS=$django_settings
RUN python3 /app/manage.py collectstatic --noinput

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=angular /app/frontend/dist /usr/share/nginx/html
COPY --from=django /app/staticfiles /usr/share/nginx/html/static
EXPOSE 80
