# Generated by Django 4.1 on 2022-12-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reci', '0024_prilog_pozitiv_prilog_reci_prilog_pozitiv_0a7479_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerisaniSpisak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='почетак генерисања')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='крај генерисања')),
            ],
            options={
                'verbose_name': 'генерисани списак речи',
                'verbose_name_plural': 'генерисани спискови речи',
            },
        ),
        migrations.CreateModel(
            name='RecZaOdluku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prvo_slovo', models.CharField(max_length=1, verbose_name='прво слово')),
                ('tekst', models.CharField(max_length=100, verbose_name='текст')),
                ('vrsta_reci', models.IntegerField(blank=True, choices=[(0, 'именица'), (1, 'глагол'), (2, 'придев'), (3, 'прилог'), (4, 'предлог'), (5, 'заменица'), (6, 'узвик'), (7, 'речца'), (8, 'везник'), (9, 'број'), (10, 'остало')], null=True, verbose_name='врста речи')),
                ('korpus_id', models.IntegerField(blank=True, null=True, verbose_name='ID речи у корпусу')),
                ('recnik_id', models.IntegerField(blank=True, null=True, verbose_name='ID речи у речнику')),
                ('odluka', models.IntegerField(choices=[(1, 'без одлуке'), (2, 'иде у речник'), (3, 'не иде у речник'), (4, 'уклонити из речника')], verbose_name='одлука')),
                ('broj_publikacija', models.IntegerField(verbose_name='број публикација')),
                ('broj_pojavljivanja', models.IntegerField(verbose_name='број појављивања')),
                ('vreme_odluke', models.DateTimeField(verbose_name='време одлуке')),
                ('donosilac_odluke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reci.userproxy', verbose_name='доносилац одлуке')),
                ('poslednje_generisanje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='decider.generisanispisak', verbose_name='последње генерисање')),
            ],
            options={
                'verbose_name': 'реч за одлуку',
                'verbose_name_plural': 'речи за одлуку',
            },
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['prvo_slovo'], name='decider_rec_prvo_sl_a38863_idx'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['tekst'], name='decider_rec_tekst_501ada_idx'),
        ),
    ]
