# Generated by Django 4.1 on 2022-12-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decider', '0002_reczaodluku_beleska'),
    ]

    operations = [
        # migrations.AddIndex(
        #     model_name='reczaodluku',
        #     index=models.Index(fields=['beleska'], name='decider_rec_beleska_f81644_idx'),
        # ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['recnik_id'], name='decider_rec_recnik__abb6de_idx'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['korpus_id'], name='decider_rec_korpus__f94f00_idx'),
        ),
    ]
