# Generated by Django 4.1 on 2022-12-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decider', '0003_reczaodluku_decider_rec_beleska_f81644_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reczaodluku',
            name='beleska',
            field=models.TextField(blank=True, max_length=1000, verbose_name='белешка'),
        ),
    ]
