# Generated by Django 4.1 on 2023-01-28 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decider', '0005_alter_reczaodluku_odluka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinamickiIzvestaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upit', models.CharField(max_length=1000)),
                ('vreme_zahteva', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време захтева')),
                ('vreme_pocetka', models.DateTimeField(blank=True, null=True, verbose_name='време почетка')),
                ('vreme_zavrsetka', models.DateTimeField(blank=True, null=True, verbose_name='време завршетка')),
                ('zavrsen', models.BooleanField(default=False, verbose_name='завршен')),
            ],
        ),
    ]
