# Generated by Django 5.0.3 on 2024-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decider', '0006_dinamickiizvestaj'),
        ('reci', '0024_prilog_pozitiv_prilog_reci_prilog_pozitiv_0a7479_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='reczaodluku',
            name='potkorpus_1',
            field=models.BooleanField(default=False, verbose_name='поткорпус 1'),
        ),
        migrations.AddField(
            model_name='reczaodluku',
            name='potkorpus_2',
            field=models.BooleanField(default=False, verbose_name='поткорпус 2'),
        ),
        migrations.AddField(
            model_name='reczaodluku',
            name='potkorpus_3',
            field=models.BooleanField(default=False, verbose_name='поткорпус 3'),
        ),
        migrations.AddField(
            model_name='reczaodluku',
            name='potkorpus_4',
            field=models.BooleanField(default=False, verbose_name='поткорпус 4'),
        ),
        migrations.AddField(
            model_name='reczaodluku',
            name='potkorpus_5',
            field=models.BooleanField(default=False, verbose_name='поткорпус 5'),
        ),
        migrations.AddField(
            model_name='reczaodluku',
            name='potkorpus_6',
            field=models.BooleanField(default=False, verbose_name='поткорпус 6'),
        ),
        migrations.AddField(
            model_name='reczaodluku',
            name='potkorpus_7',
            field=models.BooleanField(default=False, verbose_name='поткорпус 7'),
        ),
        migrations.AddField(
            model_name='reczaodluku',
            name='potkorpus_8',
            field=models.BooleanField(default=False, verbose_name='поткорпус 8'),
        ),
        migrations.AddField(
            model_name='reczaodluku',
            name='potkorpus_9',
            field=models.BooleanField(default=False, verbose_name='поткорпус 9'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['potkorpus_1'], name='decider_rec_potkorp_4a4dec_idx'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['potkorpus_2'], name='decider_rec_potkorp_ae4826_idx'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['potkorpus_3'], name='decider_rec_potkorp_ff9cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['potkorpus_4'], name='decider_rec_potkorp_f4c7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['potkorpus_5'], name='decider_rec_potkorp_ec6848_idx'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['potkorpus_6'], name='decider_rec_potkorp_80b131_idx'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['potkorpus_7'], name='decider_rec_potkorp_20eb97_idx'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['potkorpus_8'], name='decider_rec_potkorp_619777_idx'),
        ),
        migrations.AddIndex(
            model_name='reczaodluku',
            index=models.Index(fields=['potkorpus_9'], name='decider_rec_potkorp_97f3b2_idx'),
        ),
    ]
