# Generated by Django 3.1.3 on 2021-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KorpusResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osnovniOblik', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OdrednicaResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec', models.CharField(max_length=50)),
                ('vrsta', models.IntegerField()),
            ],
        ),
    ]
