# Generated by Django 3.2.7 on 2021-09-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretraga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odrednicaresponse',
            name='rbr_homo',
            field=models.IntegerField(null=True),
        ),
    ]
