# Generated by Django 5.0.3 on 2026-02-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretraga', '0002_odrednicaresponse_rbr_homo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KorpusResponse',
        ),
        migrations.DeleteModel(
            name='OdrednicaResponse',
        ),
    ]
