# Generated by Django 3.1.3 on 2020-12-07 20:12

import concurrency.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glagol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitiv', models.CharField(blank=True, max_length=50, null=True, verbose_name='инфинитив')),
                ('vid', models.IntegerField(choices=[(0, 'непознат'), (1, 'свршени'), (2, 'несвршени'), (3, 'двовидски')], verbose_name='глаголски вид')),
                ('rod', models.IntegerField(choices=[(0, 'непознат'), (1, 'прелазни'), (2, 'непрелазни'), (3, 'повратни'), (4, 'узајамно повратни')], verbose_name='глаголски род')),
                ('rgp_mj', models.CharField(blank=True, max_length=50, null=True, verbose_name='РГП муш јед')),
                ('rgp_zj', models.CharField(blank=True, max_length=50, null=True, verbose_name='РГП жен јед')),
                ('rgp_sj', models.CharField(blank=True, max_length=50, null=True, verbose_name='РГП сре јед')),
                ('rgp_mm', models.CharField(blank=True, max_length=50, null=True, verbose_name='РГП муш мно')),
                ('rgp_zm', models.CharField(blank=True, max_length=50, null=True, verbose_name='РГП жен мно')),
                ('rgp_sm', models.CharField(blank=True, max_length=50, null=True, verbose_name='РГП сре мно')),
                ('gpp', models.CharField(blank=True, max_length=50, null=True, verbose_name='ГПП')),
                ('gps', models.CharField(blank=True, max_length=50, null=True, verbose_name='ГПС')),
                ('vreme', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
            ],
            options={
                'verbose_name': 'глагол',
                'verbose_name_plural': 'глаголи',
            },
        ),
        migrations.CreateModel(
            name='Imenica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив једнине')),
                ('genjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив једнине')),
                ('datjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив једнине')),
                ('akujed', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив једнине')),
                ('vokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив једнине')),
                ('insjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал једнине')),
                ('lokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив једнине')),
                ('nommno', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив множине')),
                ('genmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив множине')),
                ('datmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив множине')),
                ('akumno', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив множине')),
                ('vokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив множине')),
                ('insmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал множине')),
                ('lokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив множине')),
                ('vreme', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
            ],
            options={
                'verbose_name': 'именица',
                'verbose_name_plural': 'именице',
            },
        ),
        migrations.CreateModel(
            name='Pridev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(blank=True, max_length=50, null=True, verbose_name='текст')),
                ('vreme', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време последње измене')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
            ],
            options={
                'verbose_name': 'придев',
                'verbose_name_plural': 'придеви',
            },
        ),
        migrations.CreateModel(
            name='VrstaImenice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'врста именице',
                'verbose_name_plural': 'врсте именица',
            },
        ),
        migrations.CreateModel(
            name='VarijantaImenice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='редни број')),
                ('nomjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив једнине')),
                ('genjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив једнине')),
                ('datjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив једнине')),
                ('akujed', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив једнине')),
                ('vokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив једнине')),
                ('insjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал једнине')),
                ('lokjed', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив једнине')),
                ('nommno', models.CharField(blank=True, max_length=50, null=True, verbose_name='номинатив множине')),
                ('genmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='генитив множине')),
                ('datmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='датив множине')),
                ('akumno', models.CharField(blank=True, max_length=50, null=True, verbose_name='акузатив множине')),
                ('vokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='вокатив множине')),
                ('insmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='инструментал множине')),
                ('lokmno', models.CharField(blank=True, max_length=50, null=True, verbose_name='локатив множине')),
                ('imenica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korpus.imenica', verbose_name='именица')),
            ],
            options={
                'verbose_name': 'варијанта именице',
                'verbose_name_plural': 'варијанте именица',
            },
        ),
        migrations.CreateModel(
            name='OblikPrideva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(blank=True, max_length=50, null=True, verbose_name='текст')),
                ('vid', models.IntegerField(choices=[(1, 'одређен'), (2, 'неодређен'), (3, 'компаратив'), (4, 'суперлатив')], verbose_name='вид')),
                ('rod', models.IntegerField(choices=[(1, 'мушки'), (2, 'женски'), (3, 'средњи')], verbose_name='род')),
                ('broj', models.IntegerField(choices=[(1, 'једнина'), (2, 'множина')], verbose_name='број')),
                ('padez', models.IntegerField(choices=[(1, 'номинатив'), (2, 'генитив'), (3, 'датив'), (4, 'акузатив'), (5, 'вокатив'), (6, 'инструментал'), (7, 'локатив')], verbose_name='падеж')),
                ('pridev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korpus.pridev', verbose_name='придев')),
            ],
            options={
                'verbose_name': 'облик придева',
                'verbose_name_plural': 'облици придева',
            },
        ),
        migrations.CreateModel(
            name='OblikGlagola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme', models.IntegerField(choices=[(1, 'презент'), (2, 'футур 1'), (3, 'аорист'), (4, 'имперфекат'), (5, 'императив')], verbose_name='глаголско време')),
                ('jd1', models.CharField(blank=True, max_length=50, null=True, verbose_name='прво лице једнине')),
                ('jd2', models.CharField(blank=True, max_length=50, null=True, verbose_name='друго лице једнине')),
                ('jd3', models.CharField(blank=True, max_length=50, null=True, verbose_name='треће лице једнине')),
                ('mn1', models.CharField(blank=True, max_length=50, null=True, verbose_name='прво лице множине')),
                ('mn2', models.CharField(blank=True, max_length=50, null=True, verbose_name='друго лице множине')),
                ('mn3', models.CharField(blank=True, max_length=50, null=True, verbose_name='треће лице множине')),
                ('glagol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korpus.glagol', verbose_name='глагол')),
            ],
        ),
        migrations.CreateModel(
            name='IzmenaPrideva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme', models.DateTimeField(verbose_name='време измене')),
                ('pridev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korpus.pridev', verbose_name='придев')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='корисник')),
            ],
            options={
                'verbose_name': 'измена придева',
                'verbose_name_plural': 'измене придева',
            },
        ),
        migrations.CreateModel(
            name='IzmenaImenice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme', models.DateTimeField(verbose_name='време измене')),
                ('imenica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korpus.imenica', verbose_name='именица')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='корисник')),
            ],
            options={
                'verbose_name': 'измена именице',
                'verbose_name_plural': 'измене именица',
            },
        ),
        migrations.CreateModel(
            name='IzmenaGlagola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme', models.DateTimeField(verbose_name='време измене')),
                ('glagol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korpus.glagol', verbose_name='глагол')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='корисник')),
            ],
            options={
                'verbose_name': 'измена глагола',
                'verbose_name_plural': 'измене глагола',
            },
        ),
        migrations.AddField(
            model_name='imenica',
            name='vrsta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='korpus.vrstaimenice', verbose_name='врста именице'),
        ),
    ]
