# Generated by Django 3.1.3 on 2021-01-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oblikglagola',
            options={'verbose_name': 'облик глагола', 'verbose_name_plural': 'облици глагола'},
        ),
    ]
