import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { MessageService } from 'primeng/api';
import { Pridev } from '../../models/pridev';
import { PridevOblik } from '../../models/pridevOblik';
import { PridevService } from '../../services/pridev/pridev.service';

@Component({
  selector: 'pridev',
  templateUrl: './pridev.component.html',
  styleUrls: ['./pridev.component.scss']
})
export class PridevComponent implements OnInit {

  @Input() pridev: Pridev;

  @Output() pridevChanged: EventEmitter<Pridev> = new EventEmitter();

  id: number;

  constructor(private messageService: MessageService, private pridevService: PridevService, private route: ActivatedRoute) {}

  ngOnInit(): void {
    if (window.location.href.endsWith('/add'))
      this.pridev = {
        tekst: '',
        oblici: this.makeOblici()
      };
    else {
      this.route.params.subscribe((params) => {
        this.id = +params.id;
      });
      this.getPridevById();
      this.pridev = { // test case, delete if getting data from the server
        id: this.id,
        tekst: 'тестирани',
        version: 1,
        oblici: [
          { tekst:'тестирани', vid:1, rod:1, broj:1, padez:1 },
          { tekst:'тестираног', vid:1, rod:1, broj:1, padez:2 },
          { tekst:'тестираном', vid:1, rod:1, broj:1, padez:3 },
          { tekst:'тестираног', vid:1, rod:1, broj:1, padez:4 },
          { tekst:'тестирани', vid:1, rod:1, broj:1, padez:5 },
          { tekst:'тестираним', vid:1, rod:1, broj:1, padez:6 },
          { tekst:'тестираном', vid:1, rod:1, broj:1, padez:7 },
          { tekst:'тестирани', vid:1, rod:1, broj:2, padez:1 },
          { tekst:'тестираних', vid:1, rod:1, broj:2, padez:2 },
          { tekst:'тестираним', vid:1, rod:1, broj:2, padez:3 },
          { tekst:'тестиране', vid:1, rod:1, broj:2, padez:4 },
          { tekst:'тестирани', vid:1, rod:1, broj:2, padez:5 },
          { tekst:'тестираним', vid:1, rod:1, broj:2, padez:6 },
          { tekst:'тестираним', vid:1, rod:1, broj:2, padez:7 },
          { tekst:'тестирана', vid:1, rod:2, broj:1, padez:1 },
          { tekst:'тестиране', vid:1, rod:2, broj:1, padez:2 },
          { tekst:'тестираној', vid:1, rod:2, broj:1, padez:3 },
          { tekst:'тестираној', vid:1, rod:2, broj:1, padez:4 },
          { tekst:'тестирана', vid:1, rod:2, broj:1, padez:5 },
          { tekst:'тестираним', vid:1, rod:2, broj:1, padez:6 },
          { tekst:'тестираној', vid:1, rod:2, broj:1, padez:7 },
          { tekst:'тестиране', vid:1, rod:2, broj:2, padez:1 },
          { tekst:'тестираних', vid:1, rod:2, broj:2, padez:2 },
          { tekst:'тестираним', vid:1, rod:2, broj:2, padez:3 },
          { tekst:'тестиране', vid:1, rod:2, broj:2, padez:4 },
          { tekst:'тестиране', vid:1, rod:2, broj:2, padez:5 },
          { tekst:'тестираним', vid:1, rod:2, broj:2, padez:6 },
          { tekst:'тестираним', vid:1, rod:2, broj:2, padez:7 },
          { tekst:'тестирано', vid:1, rod:3, broj:1, padez:1 },
          { tekst:'тестираног', vid:1, rod:3, broj:1, padez:2 },
          { tekst:'тестираном', vid:1, rod:3, broj:1, padez:3 },
          { tekst:'тестирано', vid:1, rod:3, broj:1, padez:4 },
          { tekst:'тестирано', vid:1, rod:3, broj:1, padez:5 },
          { tekst:'тестираним', vid:1, rod:3, broj:1, padez:6 },
          { tekst:'тестираном', vid:1, rod:3, broj:1, padez:7 },
          { tekst:'тестирана', vid:1, rod:3, broj:2, padez:1 },
          { tekst:'тестиране', vid:1, rod:3, broj:2, padez:2 },
          { tekst:'тестираној', vid:1, rod:3, broj:2, padez:3 },
          { tekst:'тестирану', vid:1, rod:3, broj:2, padez:4 },
          { tekst:'тестирана', vid:1, rod:3, broj:2, padez:5 },
          { tekst:'тестираном', vid:1, rod:3, broj:2, padez:6 },
          { tekst:'тестираној', vid:1, rod:3, broj:2, padez:7 },
          { tekst:'тестиран', vid:2, rod:3, broj:1, padez:1 },
          { tekst:'тестираног', vid:2, rod:1, broj:1, padez:2 },
          { tekst:'тестираном', vid:2, rod:1, broj:1, padez:3 },
          { tekst:'тестираног', vid:2, rod:1, broj:1, padez:4 },
          { tekst:'тестирани', vid:2, rod:1, broj:1, padez:5 },
          { tekst:'тестираним', vid:2, rod:1, broj:1, padez:6 },
          { tekst:'тестираном', vid:2, rod:1, broj:1, padez:7 },
          { tekst:'тестирани', vid:2, rod:1, broj:2, padez:1 },
          { tekst:'тестираних', vid:2, rod:1, broj:2, padez:2 },
          { tekst:'тестираним', vid:2, rod:1, broj:2, padez:3 },
          { tekst:'тестиране', vid:2, rod:1, broj:2, padez:4 },
          { tekst:'тестирани', vid:2, rod:1, broj:2, padez:5 },
          { tekst:'тестираним', vid:2, rod:1, broj:2, padez:6 },
          { tekst:'тестираним', vid:2, rod:1, broj:2, padez:7 },
          { tekst:'тестирана', vid:2, rod:2, broj:1, padez:1 },
          { tekst:'тестиране', vid:2, rod:2, broj:1, padez:2 },
          { tekst:'тестираној', vid:2, rod:2, broj:1, padez:3 },
          { tekst:'тестираној', vid:2, rod:2, broj:1, padez:4 },
          { tekst:'тестирана', vid:2, rod:2, broj:1, padez:5 },
          { tekst:'тестираним', vid:2, rod:2, broj:1, padez:6 },
          { tekst:'тестираној', vid:2, rod:2, broj:1, padez:7 },
          { tekst:'тестиране', vid:2, rod:2, broj:2, padez:1 },
          { tekst:'тестираних', vid:2, rod:2, broj:2, padez:2 },
          { tekst:'тестираним', vid:2, rod:2, broj:2, padez:3 },
          { tekst:'тестиране', vid:2, rod:2, broj:2, padez:4 },
          { tekst:'тестиране', vid:2, rod:2, broj:2, padez:5 },
          { tekst:'тестираним', vid:2, rod:2, broj:2, padez:6 },
          { tekst:'тестираним', vid:2, rod:2, broj:2, padez:7 },
          { tekst:'тестирано', vid:2, rod:3, broj:1, padez:1 },
          { tekst:'тестираног', vid:2, rod:3, broj:1, padez:2 },
          { tekst:'тестираном', vid:2, rod:3, broj:1, padez:3 },
          { tekst:'тестирано', vid:2, rod:3, broj:1, padez:4 },
          { tekst:'тестирано', vid:2, rod:3, broj:1, padez:5 },
          { tekst:'тестираним', vid:2, rod:3, broj:1, padez:6 },
          { tekst:'тестираном', vid:2, rod:3, broj:1, padez:7 },
          { tekst:'тестирана', vid:2, rod:3, broj:2, padez:1 },
          { tekst:'тестиране', vid:2, rod:3, broj:2, padez:2 },
          { tekst:'тестираној', vid:2, rod:3, broj:2, padez:3 },
          { tekst:'тестирану', vid:2, rod:3, broj:2, padez:4 },
          { tekst:'тестирана', vid:2, rod:3, broj:2, padez:5 },
          { tekst:'тестираном', vid:2, rod:3, broj:2, padez:6 },
          { tekst:'тестираној', vid:2, rod:3, broj:2, padez:7 },
          { tekst:'тестиранији', vid:3, rod:1, broj:1, padez:1 },
          { tekst:'тестиранијег', vid:3, rod:1, broj:1, padez:2 },
          { tekst:'тестиранијем', vid:3, rod:1, broj:1, padez:3 },
          { tekst:'тестиранијег', vid:3, rod:1, broj:1, padez:4 },
          { tekst:'тестиранији', vid:3, rod:1, broj:1, padez:5 },
          { tekst:'тестиранијим', vid:3, rod:1, broj:1, padez:6 },
          { tekst:'тестиранијем', vid:3, rod:1, broj:1, padez:7 },
          { tekst:'тестиранији', vid:3, rod:1, broj:2, padez:1 },
          { tekst:'тестиранијих', vid:3, rod:1, broj:2, padez:2 },
          { tekst:'тестиранијим', vid:3, rod:1, broj:2, padez:3 },
          { tekst:'тестираније', vid:3, rod:1, broj:2, padez:4 },
          { tekst:'тестиранији', vid:3, rod:1, broj:2, padez:5 },
          { tekst:'тестиранијим', vid:3, rod:1, broj:2, padez:6 },
          { tekst:'тестиранијим', vid:3, rod:1, broj:2, padez:7 },
          { tekst:'тестиранија', vid:3, rod:2, broj:1, padez:1 },
          { tekst:'тестираније', vid:3, rod:2, broj:1, padez:2 },
          { tekst:'тестиранијој', vid:3, rod:2, broj:1, padez:3 },
          { tekst:'тестиранију', vid:3, rod:2, broj:1, padez:4 },
          { tekst:'тестиранија', vid:3, rod:2, broj:1, padez:5 },
          { tekst:'тестиранијом', vid:3, rod:2, broj:1, padez:6 },
          { tekst:'тестиранијој', vid:3, rod:2, broj:1, padez:7 },
          { tekst:'тестираније', vid:3, rod:2, broj:2, padez:1 },
          { tekst:'тестиранијих', vid:3, rod:2, broj:2, padez:2 },
          { tekst:'тестиранијим', vid:3, rod:2, broj:2, padez:3 },
          { tekst:'тестираније', vid:3, rod:2, broj:2, padez:4 },
          { tekst:'тестираније', vid:3, rod:2, broj:2, padez:5 },
          { tekst:'тестиранијим', vid:3, rod:2, broj:2, padez:6 },
          { tekst:'тестиранијим', vid:3, rod:2, broj:2, padez:7 },
          { tekst:'тестираније', vid:3, rod:3, broj:1, padez:1 },
          { tekst:'тестиранијег', vid:3, rod:3, broj:1, padez:2 },
          { tekst:'тестиранијем', vid:3, rod:3, broj:1, padez:3 },
          { tekst:'тестираније', vid:3, rod:3, broj:1, padez:4 },
          { tekst:'тестираније', vid:3, rod:3, broj:1, padez:5 },
          { tekst:'тестиранијим', vid:3, rod:3, broj:1, padez:6 },
          { tekst:'тестиранијем', vid:3, rod:3, broj:1, padez:7 },
          { tekst:'тестиранија', vid:3, rod:3, broj:2, padez:1 },
          { tekst:'тестираније', vid:3, rod:3, broj:2, padez:2 },
          { tekst:'тестиранијој', vid:3, rod:3, broj:2, padez:3 },
          { tekst:'тестиранију', vid:3, rod:3, broj:2, padez:4 },
          { tekst:'тестиранија', vid:3, rod:3, broj:2, padez:5 },
          { tekst:'тестиранијом', vid:3, rod:3, broj:2, padez:6 },
          { tekst:'тестиранијој', vid:3, rod:3, broj:2, padez:7 },
          { tekst:'најтестиранији', vid:4, rod:1, broj:1, padez:1 },
          { tekst:'најтестиранијег', vid:4, rod:1, broj:1, padez:2 },
          { tekst:'најтестиранијем', vid:4, rod:1, broj:1, padez:3 },
          { tekst:'најтестиранијег', vid:4, rod:1, broj:1, padez:4 },
          { tekst:'најтестиранији', vid:4, rod:1, broj:1, padez:5 },
          { tekst:'најтестиранијим', vid:4, rod:1, broj:1, padez:6 },
          { tekst:'најтестиранијем', vid:4, rod:1, broj:1, padez:7 },
          { tekst:'најтестиранији', vid:4, rod:1, broj:2, padez:1 },
          { tekst:'најтестиранијих', vid:4, rod:1, broj:2, padez:2 },
          { tekst:'најтестиранијим', vid:4, rod:1, broj:2, padez:3 },
          { tekst:'најтестираније', vid:4, rod:1, broj:2, padez:4 },
          { tekst:'најтестиранији', vid:4, rod:1, broj:2, padez:5 },
          { tekst:'најтестиранијим', vid:4, rod:1, broj:2, padez:6 },
          { tekst:'најтестиранијим', vid:4, rod:1, broj:2, padez:7 },
          { tekst:'најтестиранија', vid:4, rod:2, broj:1, padez:1 },
          { tekst:'најтестираније', vid:4, rod:2, broj:1, padez:2 },
          { tekst:'најтестиранијој', vid:4, rod:2, broj:1, padez:3 },
          { tekst:'најтестиранију', vid:4, rod:2, broj:1, padez:4 },
          { tekst:'најтестиранија', vid:4, rod:2, broj:1, padez:5 },
          { tekst:'најтестиранијом', vid:4, rod:2, broj:1, padez:6 },
          { tekst:'најтестиранијој', vid:4, rod:2, broj:1, padez:7 },
          { tekst:'најтестираније', vid:4, rod:2, broj:2, padez:1 },
          { tekst:'најтестиранијих', vid:4, rod:2, broj:2, padez:2 },
          { tekst:'најтестиранијим', vid:4, rod:2, broj:2, padez:3 },
          { tekst:'најтестираније', vid:4, rod:2, broj:2, padez:4 },
          { tekst:'најтестираније', vid:4, rod:2, broj:2, padez:5 },
          { tekst:'најтестиранијим', vid:4, rod:2, broj:2, padez:6 },
          { tekst:'најтестиранијим', vid:4, rod:2, broj:2, padez:7 },
          { tekst:'најтестираније', vid:4, rod:3, broj:1, padez:1 },
          { tekst:'најтестиранијег', vid:4, rod:3, broj:1, padez:2 },
          { tekst:'најтестиранијем', vid:4, rod:3, broj:1, padez:3 },
          { tekst:'најтестираније', vid:4, rod:3, broj:1, padez:4 },
          { tekst:'најтестираније', vid:4, rod:3, broj:1, padez:5 },
          { tekst:'најтестиранијим', vid:4, rod:3, broj:1, padez:6 },
          { tekst:'најтестиранијем', vid:4, rod:3, broj:1, padez:7 },
          { tekst:'најтестиранија', vid:4, rod:3, broj:2, padez:1 },
          { tekst:'најтестираније', vid:4, rod:3, broj:2, padez:2 },
          { tekst:'најтестиранијој', vid:4, rod:3, broj:2, padez:3 },
          { tekst:'најтестиранију', vid:4, rod:3, broj:2, padez:4 },
          { tekst:'најтестиранија', vid:4, rod:3, broj:2, padez:5 },
          { tekst:'најтестиранијом', vid:4, rod:3, broj:2, padez:6 },
          { tekst:'најтестиранијој', vid:4, rod:3, broj:2, padez:7 },
        ],
      };
    }
  }

  changePridev(): void {
    this.pridevChanged.emit(this.pridev);
  }

  async getPridevById() {
    const response: any = await this.pridevService.getPridev(this.id)
      .toPromise()
      .catch(() => {
        this.messageService.add({severity:'error', summary: 'Грешка', detail: 'Тражени придев није пронађен'});
      });
    if (response) {
      this.pridev = response.map((item: Pridev) => {
        return {
          version: item.version, id: item.id, tekst: item.tekst, oblici: item.oblikprideva_set
        };
      });
    }
  }

  autofill(): void {
    let comparatives = this.pridev.oblici.filter(p => p.vid === 3);
    let superlatives = this.pridev.oblici.filter(p => p.vid === 4);
    for (let i=0; i<comparatives.length; i++)
      for (let j=0; j<superlatives.length; j++)
        if (comparatives[i].tekst !== '' && comparatives[i].rod === superlatives[j].rod && comparatives[i].broj === superlatives[j].broj && comparatives[i].padez === superlatives[j].padez)
          superlatives[j].tekst = 'нај' + comparatives[i].tekst;
    this.changePridev();
  }

  makeOblici(): PridevOblik[] {
    return [
        { tekst:'', vid:1, rod:1, broj:1, padez:1 },
        { tekst:'', vid:1, rod:1, broj:1, padez:2 },
        { tekst:'', vid:1, rod:1, broj:1, padez:3 },
        { tekst:'', vid:1, rod:1, broj:1, padez:4 },
        { tekst:'', vid:1, rod:1, broj:1, padez:5 },
        { tekst:'', vid:1, rod:1, broj:1, padez:6 },
        { tekst:'', vid:1, rod:1, broj:1, padez:7 },
        { tekst:'', vid:1, rod:1, broj:2, padez:1 },
        { tekst:'', vid:1, rod:1, broj:2, padez:2 },
        { tekst:'', vid:1, rod:1, broj:2, padez:3 },
        { tekst:'', vid:1, rod:1, broj:2, padez:4 },
        { tekst:'', vid:1, rod:1, broj:2, padez:5 },
        { tekst:'', vid:1, rod:1, broj:2, padez:6 },
        { tekst:'', vid:1, rod:1, broj:2, padez:7 },
        { tekst:'', vid:1, rod:2, broj:1, padez:1 },
        { tekst:'', vid:1, rod:2, broj:1, padez:2 },
        { tekst:'', vid:1, rod:2, broj:1, padez:3 },
        { tekst:'', vid:1, rod:2, broj:1, padez:4 },
        { tekst:'', vid:1, rod:2, broj:1, padez:5 },
        { tekst:'', vid:1, rod:2, broj:1, padez:6 },
        { tekst:'', vid:1, rod:2, broj:1, padez:7 },
        { tekst:'', vid:1, rod:2, broj:2, padez:1 },
        { tekst:'', vid:1, rod:2, broj:2, padez:2 },
        { tekst:'', vid:1, rod:2, broj:2, padez:3 },
        { tekst:'', vid:1, rod:2, broj:2, padez:4 },
        { tekst:'', vid:1, rod:2, broj:2, padez:5 },
        { tekst:'', vid:1, rod:2, broj:2, padez:6 },
        { tekst:'', vid:1, rod:2, broj:2, padez:7 },
        { tekst:'', vid:1, rod:3, broj:1, padez:1 },
        { tekst:'', vid:1, rod:3, broj:1, padez:2 },
        { tekst:'', vid:1, rod:3, broj:1, padez:3 },
        { tekst:'', vid:1, rod:3, broj:1, padez:4 },
        { tekst:'', vid:1, rod:3, broj:1, padez:5 },
        { tekst:'', vid:1, rod:3, broj:1, padez:6 },
        { tekst:'', vid:1, rod:3, broj:1, padez:7 },
        { tekst:'', vid:1, rod:3, broj:2, padez:1 },
        { tekst:'', vid:1, rod:3, broj:2, padez:2 },
        { tekst:'', vid:1, rod:3, broj:2, padez:3 },
        { tekst:'', vid:1, rod:3, broj:2, padez:4 },
        { tekst:'', vid:1, rod:3, broj:2, padez:5 },
        { tekst:'', vid:1, rod:3, broj:2, padez:6 },
        { tekst:'', vid:1, rod:3, broj:2, padez:7 },
        { tekst:'', vid:2, rod:1, broj:1, padez:1 },
        { tekst:'', vid:2, rod:1, broj:1, padez:2 },
        { tekst:'', vid:2, rod:1, broj:1, padez:3 },
        { tekst:'', vid:2, rod:1, broj:1, padez:4 },
        { tekst:'', vid:2, rod:1, broj:1, padez:5 },
        { tekst:'', vid:2, rod:1, broj:1, padez:6 },
        { tekst:'', vid:2, rod:1, broj:1, padez:7 },
        { tekst:'', vid:2, rod:1, broj:2, padez:1 },
        { tekst:'', vid:2, rod:1, broj:2, padez:2 },
        { tekst:'', vid:2, rod:1, broj:2, padez:3 },
        { tekst:'', vid:2, rod:1, broj:2, padez:4 },
        { tekst:'', vid:2, rod:1, broj:2, padez:5 },
        { tekst:'', vid:2, rod:1, broj:2, padez:6 },
        { tekst:'', vid:2, rod:1, broj:2, padez:7 },
        { tekst:'', vid:2, rod:2, broj:1, padez:1 },
        { tekst:'', vid:2, rod:2, broj:1, padez:2 },
        { tekst:'', vid:2, rod:2, broj:1, padez:3 },
        { tekst:'', vid:2, rod:2, broj:1, padez:4 },
        { tekst:'', vid:2, rod:2, broj:1, padez:5 },
        { tekst:'', vid:2, rod:2, broj:1, padez:6 },
        { tekst:'', vid:2, rod:2, broj:1, padez:7 },
        { tekst:'', vid:2, rod:2, broj:2, padez:1 },
        { tekst:'', vid:2, rod:2, broj:2, padez:2 },
        { tekst:'', vid:2, rod:2, broj:2, padez:3 },
        { tekst:'', vid:2, rod:2, broj:2, padez:4 },
        { tekst:'', vid:2, rod:2, broj:2, padez:5 },
        { tekst:'', vid:2, rod:2, broj:2, padez:6 },
        { tekst:'', vid:2, rod:2, broj:2, padez:7 },
        { tekst:'', vid:2, rod:3, broj:1, padez:1 },
        { tekst:'', vid:2, rod:3, broj:1, padez:2 },
        { tekst:'', vid:2, rod:3, broj:1, padez:3 },
        { tekst:'', vid:2, rod:3, broj:1, padez:4 },
        { tekst:'', vid:2, rod:3, broj:1, padez:5 },
        { tekst:'', vid:2, rod:3, broj:1, padez:6 },
        { tekst:'', vid:2, rod:3, broj:1, padez:7 },
        { tekst:'', vid:2, rod:3, broj:2, padez:1 },
        { tekst:'', vid:2, rod:3, broj:2, padez:2 },
        { tekst:'', vid:2, rod:3, broj:2, padez:3 },
        { tekst:'', vid:2, rod:3, broj:2, padez:4 },
        { tekst:'', vid:2, rod:3, broj:2, padez:5 },
        { tekst:'', vid:2, rod:3, broj:2, padez:6 },
        { tekst:'', vid:2, rod:3, broj:2, padez:7 },
        { tekst:'', vid:3, rod:1, broj:1, padez:1 },
        { tekst:'', vid:3, rod:1, broj:1, padez:2 },
        { tekst:'', vid:3, rod:1, broj:1, padez:3 },
        { tekst:'', vid:3, rod:1, broj:1, padez:4 },
        { tekst:'', vid:3, rod:1, broj:1, padez:5 },
        { tekst:'', vid:3, rod:1, broj:1, padez:6 },
        { tekst:'', vid:3, rod:1, broj:1, padez:7 },
        { tekst:'', vid:3, rod:1, broj:2, padez:1 },
        { tekst:'', vid:3, rod:1, broj:2, padez:2 },
        { tekst:'', vid:3, rod:1, broj:2, padez:3 },
        { tekst:'', vid:3, rod:1, broj:2, padez:4 },
        { tekst:'', vid:3, rod:1, broj:2, padez:5 },
        { tekst:'', vid:3, rod:1, broj:2, padez:6 },
        { tekst:'', vid:3, rod:1, broj:2, padez:7 },
        { tekst:'', vid:3, rod:2, broj:1, padez:1 },
        { tekst:'', vid:3, rod:2, broj:1, padez:2 },
        { tekst:'', vid:3, rod:2, broj:1, padez:3 },
        { tekst:'', vid:3, rod:2, broj:1, padez:4 },
        { tekst:'', vid:3, rod:2, broj:1, padez:5 },
        { tekst:'', vid:3, rod:2, broj:1, padez:6 },
        { tekst:'', vid:3, rod:2, broj:1, padez:7 },
        { tekst:'', vid:3, rod:2, broj:2, padez:1 },
        { tekst:'', vid:3, rod:2, broj:2, padez:2 },
        { tekst:'', vid:3, rod:2, broj:2, padez:3 },
        { tekst:'', vid:3, rod:2, broj:2, padez:4 },
        { tekst:'', vid:3, rod:2, broj:2, padez:5 },
        { tekst:'', vid:3, rod:2, broj:2, padez:6 },
        { tekst:'', vid:3, rod:2, broj:2, padez:7 },
        { tekst:'', vid:3, rod:3, broj:1, padez:1 },
        { tekst:'', vid:3, rod:3, broj:1, padez:2 },
        { tekst:'', vid:3, rod:3, broj:1, padez:3 },
        { tekst:'', vid:3, rod:3, broj:1, padez:4 },
        { tekst:'', vid:3, rod:3, broj:1, padez:5 },
        { tekst:'', vid:3, rod:3, broj:1, padez:6 },
        { tekst:'', vid:3, rod:3, broj:1, padez:7 },
        { tekst:'', vid:3, rod:3, broj:2, padez:1 },
        { tekst:'', vid:3, rod:3, broj:2, padez:2 },
        { tekst:'', vid:3, rod:3, broj:2, padez:3 },
        { tekst:'', vid:3, rod:3, broj:2, padez:4 },
        { tekst:'', vid:3, rod:3, broj:2, padez:5 },
        { tekst:'', vid:3, rod:3, broj:2, padez:6 },
        { tekst:'', vid:3, rod:3, broj:2, padez:7 },
        { tekst:'', vid:4, rod:1, broj:1, padez:1 },
        { tekst:'', vid:4, rod:1, broj:1, padez:2 },
        { tekst:'', vid:4, rod:1, broj:1, padez:3 },
        { tekst:'', vid:4, rod:1, broj:1, padez:4 },
        { tekst:'', vid:4, rod:1, broj:1, padez:5 },
        { tekst:'', vid:4, rod:1, broj:1, padez:6 },
        { tekst:'', vid:4, rod:1, broj:1, padez:7 },
        { tekst:'', vid:4, rod:1, broj:2, padez:1 },
        { tekst:'', vid:4, rod:1, broj:2, padez:2 },
        { tekst:'', vid:4, rod:1, broj:2, padez:3 },
        { tekst:'', vid:4, rod:1, broj:2, padez:4 },
        { tekst:'', vid:4, rod:1, broj:2, padez:5 },
        { tekst:'', vid:4, rod:1, broj:2, padez:6 },
        { tekst:'', vid:4, rod:1, broj:2, padez:7 },
        { tekst:'', vid:4, rod:2, broj:1, padez:1 },
        { tekst:'', vid:4, rod:2, broj:1, padez:2 },
        { tekst:'', vid:4, rod:2, broj:1, padez:3 },
        { tekst:'', vid:4, rod:2, broj:1, padez:4 },
        { tekst:'', vid:4, rod:2, broj:1, padez:5 },
        { tekst:'', vid:4, rod:2, broj:1, padez:6 },
        { tekst:'', vid:4, rod:2, broj:1, padez:7 },
        { tekst:'', vid:4, rod:2, broj:2, padez:1 },
        { tekst:'', vid:4, rod:2, broj:2, padez:2 },
        { tekst:'', vid:4, rod:2, broj:2, padez:3 },
        { tekst:'', vid:4, rod:2, broj:2, padez:4 },
        { tekst:'', vid:4, rod:2, broj:2, padez:5 },
        { tekst:'', vid:4, rod:2, broj:2, padez:6 },
        { tekst:'', vid:4, rod:2, broj:2, padez:7 },
        { tekst:'', vid:4, rod:3, broj:1, padez:1 },
        { tekst:'', vid:4, rod:3, broj:1, padez:2 },
        { tekst:'', vid:4, rod:3, broj:1, padez:3 },
        { tekst:'', vid:4, rod:3, broj:1, padez:4 },
        { tekst:'', vid:4, rod:3, broj:1, padez:5 },
        { tekst:'', vid:4, rod:3, broj:1, padez:6 },
        { tekst:'', vid:4, rod:3, broj:1, padez:7 },
        { tekst:'', vid:4, rod:3, broj:2, padez:1 },
        { tekst:'', vid:4, rod:3, broj:2, padez:2 },
        { tekst:'', vid:4, rod:3, broj:2, padez:3 },
        { tekst:'', vid:4, rod:3, broj:2, padez:4 },
        { tekst:'', vid:4, rod:3, broj:2, padez:5 },
        { tekst:'', vid:4, rod:3, broj:2, padez:6 },
        { tekst:'', vid:4, rod:3, broj:2, padez:7 }
    ];
  }
}
